<?php
declare(strict_types=1);
const APP_VERSION='2.0.0';
const SCHEMA_VERSION=4;
function json_response(array $data,int $status=200): never {http_response_code($status);header('Content-Type: application/json; charset=utf-8');echo json_encode($data,JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR);exit;}
function is_https(): bool {return (!empty($_SERVER['HTTPS'])&&$_SERVER['HTTPS']!=='off');}
function local_request(): bool {return in_array($_SERVER['REMOTE_ADDR']??'',['127.0.0.1','::1'],true);}
header('X-Content-Type-Options: nosniff');header('X-Frame-Options: DENY');header('Referrer-Policy: same-origin');header('Cache-Control: no-store');
header("Content-Security-Policy: default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self'; connect-src 'self'; frame-ancestors 'none'; base-uri 'self'; form-action 'self'");
if(is_https())header('Strict-Transport-Security: max-age=31536000');
if(!is_https()&&!local_request()){http_response_code(400);exit('برای محافظت از حساب و نمرات، سایت را با HTTPS باز کنید.');}
ini_set('session.use_strict_mode','1');ini_set('session.use_only_cookies','1');ini_set('session.gc_maxlifetime','28800');session_name('poodman_session');session_set_cookie_params(['lifetime'=>0,'path'=>rtrim(str_replace('\\','/',dirname($_SERVER['SCRIPT_NAME']??'/')),'/').'/', 'secure'=>is_https(),'httponly'=>true,'samesite'=>'Strict']);session_start();
if(isset($_SESSION['seen'])&&time()-$_SESSION['seen']>28800){$_SESSION=[];session_regenerate_id(true);}$_SESSION['seen']=time();
if(empty($_SESSION['csrf']))$_SESSION['csrf']=bin2hex(random_bytes(32));
function csrf_check(?string $provided=null): void {if(!hash_equals($_SESSION['csrf'], $provided??($_SERVER['HTTP_X_CSRF_TOKEN']??'')))json_response(['error'=>'نشست معتبر نیست؛ صفحه را تازه کنید.'],403);}
function db(): PDO {static $db;if($db)return $db;$file=__DIR__.'/config.php';if(!is_file($file))json_response(['error'=>'سامانه هنوز نصب نشده است. صفحه نصب اولیه را باز کنید.'],503);$c=require $file;try{$db=new PDO('mysql:host='.$c['host'].';port='.$c['port'].';dbname='.$c['database'].';charset=utf8mb4',$c['user'],$c['password'],[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_EMULATE_PREPARES=>false,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);}catch(Throwable $e){error_log('Poodman database unavailable');json_response(['error'=>'پایگاه داده در دسترس نیست؛ تنظیمات هاست را بررسی کنید.'],503);}return $db;}
function user(): ?array {if(empty($_SESSION['uid']))return null;$s=db()->prepare('SELECT * FROM pdm_users WHERE id=?');$s->execute([$_SESSION['uid']]);$u=$s->fetch();if(!$u||!(bool)($u['active']??1)||(int)$u['auth_version']!==($_SESSION['auth_version']??0)){unset($_SESSION['uid']);return null;}return $u;}
function require_user(bool $admin=false): array {$u=user();if(!$u)json_response(['error'=>'نشست پایان یافته؛ دوباره وارد شوید.'],401);if($admin&&$u['role']!=='admin')json_response(['error'=>'این کار فقط برای مدیر مجاز است.'],403);return $u;}
function workspace(array $u,?int $ownerId=null): array {$s=db()->prepare('SELECT payload,revision FROM pdm_workspaces WHERE user_id=?');$s->execute([$ownerId??$u['id']]);$r=$s->fetch();return ['workspaceId'=>(int)($ownerId??$u['id']),'user'=>['id'=>(int)$u['id'],'email'=>$u['email'],'role'=>$u['role']],'data'=>json_decode($r['payload'],false,64,JSON_THROW_ON_ERROR),'revision'=>(int)$r['revision'],'csrf'=>$_SESSION['csrf']];}
function empty_payload(string $name): string {return json_encode(['schema'=>1,'profile'=>['name'=>$name,'school'=>'','year'=>'۱۴۰۵–۱۴۰۶'],'classes'=>[],'students'=>[],'courses'=>[],'sessions'=>[],'finals'=>new stdClass()],JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR);}
function password_check(mixed $password): string {if(!is_string($password)||strlen($password)<12||strlen($password)>72)throw new InvalidArgumentException('رمز باید بین ۱۲ و ۷۲ بایت باشد.');return $password;}
function throttle(string $key,int $limit,int $seconds=900): void {$key=hash('sha256',$key);$q=db()->prepare('INSERT INTO pdm_rate_limits (rate_key,started,attempts) VALUES (?,UNIX_TIMESTAMP(),1) ON DUPLICATE KEY UPDATE attempts=IF(started<UNIX_TIMESTAMP()-?,1,attempts+1),started=IF(started<UNIX_TIMESTAMP()-?,UNIX_TIMESTAMP(),started)');$q->execute([$key,$seconds,$seconds]);$q=db()->prepare('SELECT attempts FROM pdm_rate_limits WHERE rate_key=?');$q->execute([$key]);if((int)$q->fetchColumn()>$limit)json_response(['error'=>'تعداد تلاش‌ها زیاد است؛ ۱۵ دقیقه دیگر تلاش کنید.'],429);if(random_int(1,100)===1)db()->exec('DELETE FROM pdm_rate_limits WHERE started<UNIX_TIMESTAMP()-86400');}
