<?php
declare(strict_types=1);
// All writes are checked against the canonical server copy, never client permissions.
const SCHOOL_PERMISSIONS=['structure','students','subjects','teachers','assign','grades','office','routing','sms','announce','promotion'];
function school_id(): string{return bin2hex(random_bytes(16));}
function school_find(array $rows,string $id): ?array{foreach($rows as $r)if(($r['id']??null)===$id)return $r;return null;}
function school_actor(array $u): string{return $u['role']==='admin'?'admin':(string)($u['actor_id']??'');}
function school_can(array $life,string $actor,string $permission): bool{if($actor==='admin'||$actor==='deputy')return true;$person=school_find($life['people'],$actor);if(($person['roleId']??'')==='deputy')return true;$role=school_find($life['roles'],(string)($person['roleId']??''));return in_array($permission,$role['permissions']??[],true);}
function school_require(bool $condition,string $message='این تغییر در دسترسی شما نیست.'): void{if(!$condition)throw new InvalidArgumentException($message);}
function school_empty(): array{return ['d'=>['years'=>[['id'=>school_id(),'name'=>'۱۴۰۵–۱۴۰۶','archived'=>false]],'majors'=>[],'grades'=>[['id'=>'g10','name'=>'دهم','order'=>10],['id'=>'g11','name'=>'یازدهم','order'=>11],['id'=>'g12','name'=>'دوازدهم','order'=>12]],'classes'=>[],'students'=>[],'enrollments'=>[],'teachers'=>[],'subjects'=>[],'offerings'=>[],'sessions'=>[],'finals'=>[],'incidents'=>[],'attendanceFollowup'=>[],'customFields'=>[]],'life'=>['roles'=>[],'people'=>[],'notices'=>[],'messages'=>[],'routes'=>['default'=>'admin'],'dispatches'=>[],'tasks'=>[],'submissions'=>[],'announcements'=>[],'contacts'=>[],'sms'=>[],'smsConfig'=>['provider'=>'سرویس انتخاب نشده','sender'=>''],'notificationPrefs'=>[]]];}
function school_wire(mixed $v,?string $key=null): mixed{if(!is_array($v))return $v;$out=[];foreach($v as $k=>$x)$out[$k]=school_wire($x,(string)$k);return in_array($key,['finals','attendanceFollowup','routes','contacts','notificationPrefs','followups','records','answers','extra','gradeScales'],true)?(object)$out:$out;}
function school_same(mixed $a,mixed $b): bool{return $a==$b;}
function school_notify(array &$l,string $to,string $title,string $body,string $page): void{$l['notices'][]=['id'=>school_id(),'to'=>$to,'title'=>$title,'body'=>$body,'page'=>$page,'date'=>date('Y-m-d'),'read'=>false];}
function school_visible(array $state,string $actor): array{
 $d=$state['d'];$l=$state['life'];$teacher=str_starts_with($actor,'teacher:')?substr($actor,8):null;$student=str_starts_with($actor,'student:')?substr($actor,8):null;$admin=$actor==='admin';
 $roster=$admin||school_can($l,$actor,'students')||school_can($l,$actor,'office')||school_can($l,$actor,'grades');
 $classIds=[];if($teacher)foreach($d['offerings'] as $o)if($o['teacherId']===$teacher)$classIds[]=$o['classId'];if($student)foreach($d['enrollments'] as $e)if($e['studentId']===$student&&$e['status']==='active')$classIds[]=$e['classId'];
 $courseIds=[];foreach($d['offerings'] as $o)if(($teacher&&$o['teacherId']===$teacher)||($student&&in_array($o['classId'],$classIds,true))||(!$teacher&&!$student&&($roster||school_can($l,$actor,'assign')||school_can($l,$actor,'subjects')||school_can($l,$actor,'structure'))))$courseIds[]=$o['id'];
 $allClasses=!$teacher&&!$student&&($roster||school_can($l,$actor,'structure')||school_can($l,$actor,'assign')||school_can($l,$actor,'subjects'));
 $d['classes']=array_values(array_filter($d['classes'],fn($c)=>$allClasses||in_array($c['id'],$classIds,true)));
 $d['offerings']=array_values(array_filter($d['offerings'],fn($o)=>in_array($o['id'],$courseIds,true)));
 $d['enrollments']=array_values(array_filter($d['enrollments'],fn($e)=>$student?$e['studentId']===$student:($roster||in_array($e['classId'],$classIds,true))));
 $studentIds=array_column($d['enrollments'],'studentId');$d['students']=array_values(array_filter($d['students'],fn($s)=>$roster||in_array($s['id'],$studentIds,true)));
 if($teacher||$student)foreach($d['students'] as &$s){unset($s['phone'],$s['extra']);}unset($s);
 $gradeRead=$teacher||$student||school_can($l,$actor,'grades');$office=school_can($l,$actor,'office');
 $d['sessions']=array_values(array_filter($d['sessions'],fn($s)=>in_array($s['courseId'],$courseIds,true)&&($gradeRead||$office)));
 foreach($d['sessions'] as &$s){foreach($s['records'] as $id=>&$r){if($student&&$id!==$student)unset($s['records'][$id]);elseif(!$gradeRead){$r['marks']=[];$r['note']='';$r['asked']=false;}}unset($r);}unset($s);
 $d['finals']=array_filter($d['finals'],function($f,$key)use($gradeRead,$courseIds,$student){$p=explode(':',$key);return $gradeRead&&count($p)===3&&in_array($p[0],$courseIds,true)&&(!$student||$p[2]===$student);},ARRAY_FILTER_USE_BOTH);
 $d['incidents']=$office?$d['incidents']:[];$d['attendanceFollowup']=$office?$d['attendanceFollowup']:[];
 if(!school_can($l,$actor,'teachers'))foreach($d['teachers'] as &$t){unset($t['phone']);}unset($t);
 $l['messages']=array_values(array_filter($l['messages'],fn($m)=>$m['from']===$actor||$m['to']===$actor));$l['notices']=array_values(array_filter($l['notices'],fn($n)=>$n['to']===$actor));
 $l['dispatches']=array_values(array_filter($l['dispatches'],fn($x)=>$office&&($admin||$x['to']===$actor)));
 $l['tasks']=array_values(array_filter($l['tasks'],fn($t)=>in_array($t['courseId'],$courseIds,true)&&($teacher||($student&&$t['published']))));
 if($student)foreach($l['tasks'] as &$t)foreach($t['questions'] as &$q)unset($q['correct']);unset($t,$q);
 $taskIds=array_column($l['tasks'],'id');$l['submissions']=array_values(array_filter($l['submissions'],fn($s)=>in_array($s['taskId'],$taskIds,true)&&($teacher||$s['studentId']===$student)));
 if($student)foreach($l['submissions'] as &$s)if(!$s['released']){$s['score']=null;$s['feedback']='';}unset($s);
 $l['contacts']=school_can($l,$actor,'sms')||$office?$l['contacts']:[];$l['sms']=school_can($l,$actor,'sms')?$l['sms']:[];
 $l['announcements']=array_values(array_filter($l['announcements'],fn($a)=>$a['audience']==='all'||($student?$a['audience']==='students':$a['audience']==='staff')));
 $l['notificationPrefs']=isset($l['notificationPrefs'][$actor])?[$actor=>$l['notificationPrefs'][$actor]]:[];
 return ['d'=>$d,'life'=>$l];
}
function school_merge_rows(array $original,array $visible,array $incoming,callable $check): array{
 school_require(array_is_list($incoming)&&count($incoming)<=20000,'فهرست نامعتبر یا بیش از ظرفیت است.');$seen=[];
 foreach($incoming as $row){school_require(is_array($row)&&is_string($row['id']??null)&&preg_match('/^[\p{L}\p{N}_:-]{1,100}$/u',$row['id'])===1,'شناسه معتبر نیست.');$id=$row['id'];school_require(!isset($seen[$id]),'شناسه تکراری است.');$seen[$id]=true;$old=school_find($original,$id);$shown=school_find($visible,$id);school_require(!$old||$shown!==null);if($shown!==null&&school_same($row,$shown))continue;$new=$check($old,$row);if($old){foreach($original as $i=>$r)if($r['id']===$id){$original[$i]=$new;break;}}else $original[]=$new;}
 foreach($visible as $r)school_require(isset($seen[$r['id']]),'حذف مستقیم سوابق مجاز نیست.');return $original;
}
function school_only(array $old,array $new,array $fields): void{foreach(array_unique(array_merge(array_keys($old),array_keys($new))) as $key)if(!in_array($key,$fields,true))school_require(school_same($old[$key]??null,$new[$key]??null),'تغییر فیلد محافظت‌شده مجاز نیست: '.$key);}
function school_validate(array $state): void{
 $d=$state['d'];$l=$state['life'];$seen=[];foreach(['years','majors','grades','classes','students','teachers','subjects','offerings','enrollments','sessions','incidents','customFields'] as $key){school_require(isset($d[$key])&&is_array($d[$key])&&array_is_list($d[$key]),'ساختار داده معتبر نیست: '.$key);$ids=array_column($d[$key],'id');school_require(count(array_unique($ids))===count($ids),'شناسه تکراری است.');}
 foreach($d['classes'] as $c)school_require(school_find($d['years'],$c['yearId'])&&school_find($d['majors'],$c['majorId'])&&school_find($d['grades'],$c['gradeId']),'رشته، پایه یا سال کلاس معتبر نیست.');
 foreach($d['students'] as $s){foreach($s['extra']??[] as $key=>$value){$field=school_find($d['customFields'],(string)$key);school_require($field&&is_string($value)&&strlen($value)<=6000,'مشخصه دانش‌آموز معتبر نیست.');if($value!==''){if($field['type']==='number')school_require(is_numeric($value),'مشخصه عددی معتبر نیست.');if($field['type']==='date')school_require(school_date($value),'تاریخ مشخصه معتبر نیست.');}}school_require(!empty($s['name'])&&!empty($s['father'])&&!empty($s['code']),'نام، نام پدر و کد دانش‌آموز لازم است.');school_require(!isset($seen['code:'.$s['code']]),'کد دانش‌آموز تکراری است.');$seen['code:'.$s['code']]=1;school_require(empty($s['phone'])||preg_match('/^09[0-9]{9}$/D',$s['phone'])===1,'شماره دانش‌آموز معتبر نیست.');}
 foreach($d['customFields'] as $field)school_require(!empty($field['name'])&&in_array($field['type'],['text','number','date'],true)&&is_bool($field['required']),'مشخصه دلخواه معتبر نیست.');
 foreach($d['teachers'] as $t)school_require(!empty($t['name'])&&filter_var($t['email'],FILTER_VALIDATE_EMAIL)&&preg_match('/^09[0-9]{9}$/D',$t['phone']??'')===1,'نام، ایمیل و شماره همراه معتبر معلم الزامی است.');
 foreach($d['enrollments'] as $e){school_require(school_find($d['students'],$e['studentId'])&&school_find($d['years'],$e['yearId']),'پرونده ثبت‌نام نامعتبر است.');$key=$e['yearId'].':'.$e['studentId'];school_require(!isset($seen[$key]),'هر دانش‌آموز فقط یک ثبت‌نام در هر سال دارد.');$seen[$key]=1;if($e['status']==='active'){ $c=school_find($d['classes'],(string)$e['classId']);school_require($c&&$c['yearId']===$e['yearId'],'سال و کلاس ثبت‌نام سازگار نیستند.');}else school_require($e['status']==='graduated'&&$e['classId']===null);}
 foreach($d['offerings'] as $o){$c=school_find($d['classes'],$o['classId']);$s=school_find($d['subjects'],$o['subjectId']);school_require($c&&$s&&$s['gradeId']===$c['gradeId']&&($s['majorId']==='all'||$s['majorId']===$c['majorId']),'درس با پایه و رشته کلاس سازگار نیست.');school_require(empty($o['teacherId'])||school_find($d['teachers'],$o['teacherId']),'معلم درس معتبر نیست.');school_require(count($o['modules'])===5,'هر درس باید پنج پودمان داشته باشد.');foreach($o['modules'] as $m)school_require(in_array($m['competencies'],[1,2],true));school_formula($o['formula']??[]);}
 foreach($d['sessions'] as $s){$o=school_find($d['offerings'],$s['courseId']);school_require($o&&is_int($s['module'])&&$s['module']>=0&&$s['module']<5&&school_date($s['date']),'جلسه معتبر نیست.');foreach($s['records'] as $id=>$r){school_require(school_find($d['students'],(string)$id)&&in_array($r['attendance'],['unset','present','absent','late','excused'],true));foreach($r['marks'] as $m){$max=$m['max']??20;school_require(is_string($m['type']??null)&&trim($m['type'])!==''&&strlen($m['type'])<=100&&is_int($m['competency']??null)&&$m['competency']>=1&&$m['competency']<=$o['modules'][$s['module']]['competencies'],'نوع یا شایستگی نمره معتبر نیست.');school_require(is_numeric($max)&&$max>0&&$max<=1000&&is_numeric($m['value'])&&$m['value']>=0&&$m['value']<=(in_array($m['type'],['مثبت','منفی'],true)?1000:$max),'نمره با بارم سازگار نیست.');}}}
 foreach($l['roles'] as $r)school_require(!empty($r['name'])&&!array_diff($r['permissions'],SCHOOL_PERMISSIONS),'دسترسی سمت نامعتبر است.');
}
function school_date(mixed $value): bool{if(!is_string($value)||!preg_match('/^(\d{4})-(\d{2})-(\d{2})$/D',$value,$m))return false;return checkdate((int)$m[2],(int)$m[3],(int)$m[1]);}
function school_formula(array $formula): void{$expression=$formula['expression']??'';school_require(is_string($expression)&&strlen($expression)<=512&&preg_match('/^[0-9a-zA-Z_+*\/%(),.<>!=\s-]+$/D',$expression)===1,'فرمول نمره معتبر نیست.');preg_match_all('/[a-zA-Z_]+/',$expression,$m);$allowed=['avg','count','positive','negative','attendance','classwork','workshop','written','oral','discipline','presentation','homework','min','max','if','round'];school_require(!array_diff($m[0],$allowed),'متغیر فرمول شناخته‌شده نیست.');foreach(['minimum','high','pass'] as $key)school_require(is_numeric($formula[$key]??null)&&$formula[$key]>=0&&$formula[$key]<=20,'حد فرمول معتبر نیست.');school_require($formula['minimum']<=$formula['high']&&in_array((float)($formula['round']??0),[0.5,1.0],true),'گردکردن فرمول معتبر نیست.');}
function school_course_active(array $d,string $id): bool{$o=school_find($d['offerings'],$id);$c=$o?school_find($d['classes'],$o['classId']):null;$y=$c?school_find($d['years'],$c['yearId']):null;return $y&&!$y['archived'];}
function school_course_edit(array $d,string $actor,string $courseId): bool{$o=school_find($d['offerings'],$courseId);$c=$o?school_find($d['classes'],$o['classId']):null;$y=$c?school_find($d['years'],$c['yearId']):null;return $o&&$y&&!$y['archived']&&$actor==='teacher:'.$o['teacherId'];}
function school_student_course(array $d,string $studentId,string $courseId): bool{$o=school_find($d['offerings'],$courseId);$c=$o?school_find($d['classes'],$o['classId']):null;if(!$c)return false;foreach($d['enrollments'] as $e)if($e['studentId']===$studentId&&$e['classId']===$c['id']&&$e['yearId']===$c['yearId']&&$e['status']==='active')return true;return false;}
function school_message_allowed(array $d,array $l,string $from,string $to): bool{
 if($from===$to)return false;$student=str_starts_with($from,'student:')?$from:(str_starts_with($to,'student:')?$to:null);$teacher=str_starts_with($from,'teacher:')?$from:(str_starts_with($to,'teacher:')?$to:null);
 $exists=fn($id)=>in_array($id,['admin','deputy'],true)||school_find($l['people'],$id)||str_starts_with($id,'teacher:')&&school_find($d['teachers'],substr($id,8))||str_starts_with($id,'student:')&&school_find($d['students'],substr($id,8));if(!$exists($from)||!$exists($to))return false;if(!$student)return true;if(!$teacher)return false;
 foreach($d['offerings'] as $o)if('teacher:'.$o['teacherId']===$teacher&&school_student_course($d,substr($student,8),$o['id']))return true;return false;
}
function school_merge(array $state,array $input,string $actor): array{
 school_require(isset($input['d'],$input['life'])&&is_array($input['d'])&&is_array($input['life']),'ساختار درخواست معتبر نیست.');$visible=school_visible($state,$actor);$d=$state['d'];$l=$state['life'];$nd=$input['d'];$nl=$input['life'];
 $permissions=['years'=>'promotion','majors'=>'structure','grades'=>'structure','classes'=>'structure','students'=>'students','enrollments'=>'students','teachers'=>'teachers','subjects'=>'subjects','customFields'=>'students'];
 foreach($permissions as $key=>$permission){school_require(isset($nd[$key])&&is_array($nd[$key]));$d[$key]=school_merge_rows($d[$key],$visible['d'][$key],$nd[$key],function($old,$row)use($l,$actor,$permission,$key,$state){if(in_array($key,['classes','enrollments'],true)){ $year=school_find($state['d']['years'],$row['yearId']);school_require(!$year||!$year['archived'],'سال بایگانی‌شده قابل تغییر نیست.');}if($key==='students')foreach($state['d']['customFields'] as $f)if($f['required'])school_require(trim($row['extra'][$f['id']]??'')!=='','مشخصه الزامی دانش‌آموز تکمیل نشده است.');school_require(school_can($l,$actor,$permission)||in_array($key,['classes','enrollments'],true)&&school_can($l,$actor,'promotion'));if($key==='enrollments'&&$old)school_only($old,$row,['classId','status']);if($key==='classes'&&$old)school_only($old,$row,['name']);if($key==='years'&&$old)school_require(!$old['archived']||$row['archived'],'بازکردن سال بایگانی‌شده مجاز نیست.');return $row;});}
 $d['offerings']=school_merge_rows($d['offerings'],$visible['d']['offerings'],$nd['offerings']??[],function($old,$row)use($state,$l,$actor){if($old&&school_course_edit($state['d'],$actor,$old['id'])){school_only($old,$row,['modules','formula','gradeScales']);return $row;}school_require(school_can($l,$actor,'assign')||school_can($l,$actor,'subjects')||school_can($l,$actor,'structure')||school_can($l,$actor,'promotion'));if($old)school_only($old,$row,['teacherId','name']);else{school_require(count($row['modules']??[])===5);school_require(!school_find($state['d']['offerings'],$row['id']));}return $row;});
 $changedStudents=[];
 $d['sessions']=school_merge_rows($d['sessions'],$visible['d']['sessions'],$nd['sessions']??[],function($old,$row)use($state,$actor,$l,&$changedStudents){$d=$state['d'];$course=$row['courseId']??'';school_require(school_course_active($d,$course),'سال بایگانی‌شده قابل تغییر نیست.');$teacher=school_course_edit($d,$actor,$course);school_require($teacher||school_can($l,$actor,'office')&&$old!==null);if($old)school_only($old,$row,['records']);
 if(!$teacher){school_only($old,$row,['records']);school_require(array_keys($old['records'])===array_keys($row['records']));foreach($row['records'] as $id=>&$record){$original=$old['records'][$id];$shown=school_can($l,$actor,'grades')?$original:array_merge($original,['marks'=>[],'note'=>'','asked'=>false]);school_only($shown,$record,['attendance']);$record=array_merge($original,['attendance'=>$record['attendance']]);}unset($record);return $row;}
 foreach($row['records'] as $id=>$r){$before=$old['records'][$id]??null;if(school_same($before,$r))continue;school_require(school_student_course($d,(string)$id,$course),'دانش‌آموز عضو این کلاس نیست.');if(!school_same($before['marks']??[],$r['marks']??[]))$changedStudents[$id]=true;}
 if($old)foreach($old['records'] as $id=>$r)school_require(isset($row['records'][$id]),'حذف سابقه جلسه مجاز نیست.');return $row;});
 foreach($nd['finals']??[] as $key=>$f){if(school_same($visible['d']['finals'][$key]??null,$f))continue;$p=explode(':',$key);school_require(count($p)===3&&school_course_edit($state['d'],$actor,$p[0])&&school_student_course($state['d'],$p[2],$p[0])&&ctype_digit($p[1])&&(int)$p[1]<5);foreach(['continuous'=>5,'competency'=>3,'total'=>20] as $field=>$max){$v=$f[$field]??null;school_require($v===null||is_numeric($v)&&$v>=0&&$v<=$max,'نمره پودمانی نامعتبر است.');}foreach($f['competencies']??[] as $v)school_require($v===null||in_array($v,[1,2,3],true));$d['finals'][$key]=$f;$changedStudents[$p[2]]=true;}
 $d['incidents']=school_merge_rows($d['incidents'],$visible['d']['incidents'],$nd['incidents']??[],function($old,$row)use($d,$l,$actor){school_require(school_can($l,$actor,'office')||!$old&&str_starts_with($actor,'teacher:')&&count(array_filter($d['offerings'],fn($o)=>$o['classId']===$row['classId']&&$actor==='teacher:'.$o['teacherId']))>0);if($old)school_only($old,$row,['title','detail','followup','status','date']);else{$row['author']=$actor;if(!school_can($l,$actor,'office')){$row['followup']='';$row['status']='open';}}school_require(in_array($row['status'],['open','in_progress','resolved'],true)&&school_date($row['date']));return $row;});
 if(!school_same($nd['attendanceFollowup']??[],$visible['d']['attendanceFollowup'])){school_require(school_can($l,$actor,'office'));$d['attendanceFollowup']=array_merge($d['attendanceFollowup'],$nd['attendanceFollowup']);}
 foreach(['roles','people'] as $key)$l[$key]=school_merge_rows($l[$key],$visible['life'][$key],$nl[$key]??[],function($old,$row)use($actor,$key){school_require($actor==='admin');if($key==='people')school_require(str_starts_with($row['id'],'staff:')||$old!==null);return $row;});
 if(!school_same($nl['routes']??[],$visible['life']['routes'])){school_require(school_can($l,$actor,'routing'));foreach($nl['routes'] as $id=>$to)school_require(school_can($l,$to,'office'),'مسئول انتخاب‌شده مجوز پیگیری ندارد.');$l['routes']=$nl['routes'];}
 $l['messages']=school_merge_rows($l['messages'],$visible['life']['messages'],$nl['messages']??[],function($old,$row)use($d,&$l,$actor){if($old){school_require($old['to']===$actor);school_only($old,$row,['read']);$old['read']=true;return $old;}school_require(($row['from']??null)===$actor&&school_message_allowed($d,$l,$actor,$row['to'])&&!empty(trim($row['text']??'')));$row=['id'=>$row['id'],'from'=>$actor,'to'=>$row['to'],'text'=>trim($row['text']),'date'=>date('Y-m-d'),'read'=>false];school_notify($l,$row['to'],'پیام جدید','پیام تازه‌ای دریافت کرده‌اید.','hub-messages');return $row;});
 // Notices are generated on the server. Clients can only mark their existing notices read.
 foreach($nl['notices']??[] as $n)foreach($l['notices'] as &$stored)if($stored['id']===$n['id']&&$stored['to']===$actor&&($n['read']??false))$stored['read']=true;unset($stored);
 foreach($nl['notificationPrefs']??[] as $id=>$pref){school_require($id===$actor);$l['notificationPrefs'][$id]=['messages'=>(bool)($pref['messages']??true),'learning'=>(bool)($pref['learning']??true)];}
 $l['tasks']=school_merge_rows($l['tasks'],$visible['life']['tasks'],$nl['tasks']??[],function($old,$row)use($d,&$l,$actor){school_require(!$old&&school_course_edit($d,$actor,$row['courseId']??''),'ویرایش فعالیت منتشرشده مجاز نیست.');school_require(in_array($row['kind'],['assignment','quiz'],true)&&school_date($row['due'])&&is_numeric($row['max'])&&$row['max']>0&&$row['max']<=1000&&!empty(trim($row['title']))&&!empty(trim($row['body'])));if($row['kind']==='quiz'){school_require(count($row['questions'])>0&&count($row['questions'])<=100);foreach($row['questions'] as $q)school_require(count($q['options'])===4&&is_int($q['correct'])&&$q['correct']>=0&&$q['correct']<4&&!empty(trim($q['text']))&&!in_array('',array_map('trim',$q['options']),true));}$row['published']=true;foreach($d['students'] as $s)if(school_student_course($d,$s['id'],$row['courseId']))school_notify($l,'student:'.$s['id'],'فعالیت آموزشی جدید',$row['title'],'hub-learning');return $row;});
 $l['submissions']=school_merge_rows($l['submissions'],$visible['life']['submissions'],$nl['submissions']??[],function($old,$row)use($d,&$l,$actor){$t=school_find($l['tasks'],$row['taskId']??'');school_require($t!==null);$student=str_starts_with($actor,'student:')?substr($actor,8):null;
 if($student){school_require($row['studentId']===$student&&school_course_active($d,$t['courseId'])&&school_student_course($d,$student,$t['courseId'])&&$t['published']&&$t['due']>=date('Y-m-d'));school_require(!$old||!$old['released']&&$t['kind']==='assignment');if($old)school_only($old,$row,['text','file','answers','date','score','feedback','released']);foreach($l['submissions'] as $s)school_require($s['id']===$row['id']||$s['taskId']!==$t['id']||$s['studentId']!==$student,'پاسخ قبلاً ثبت شده است.');$row['date']=date('Y-m-d');$row['score']=null;$row['feedback']='';$row['released']=false;
 if($t['kind']==='quiz'){$correct=0;foreach($t['questions'] as $q){$answer=$row['answers'][$q['id']]??null;school_require(is_int($answer)&&$answer>=0&&$answer<4,'پاسخ همه پرسش‌ها لازم است.');if($answer===$q['correct'])$correct++;}$row['score']=round($correct/count($t['questions'])*$t['max'],2);$row['released']=true;}else school_require(!empty(trim($row['text']??''))||!empty($row['file']));
 if(!empty($row['file']))school_require(preg_match('~^\./school-api.php\?action=attachment&id=[a-f0-9]{32}$~D',$row['file']['url']??'')===1,'فایل باید از مسیر امن بارگذاری شود.');$o=school_find($d['offerings'],$t['courseId']);school_notify($l,'teacher:'.$o['teacherId'],'پاسخ جدید دانش‌آموز',$t['title'],'hub-learning');if($row['released'])school_notify($l,$actor,'نتیجه آزمون آماده است',$t['title'],'hub-grades');return $row;
 }school_require($old&&school_course_edit($d,$actor,$t['courseId']));school_only($old,$row,['score','feedback','released']);school_require(is_numeric($row['score'])&&$row['score']>=0&&$row['score']<=$t['max']);$row['released']=true;school_notify($l,'student:'.$row['studentId'],'نمره و بازخورد جدید',$t['title'],'hub-grades');return $row;});
 foreach($nl['contacts']??[] as $id=>$c){if(school_same($visible['life']['contacts'][$id]??null,$c))continue;school_require(school_can($l,$actor,'sms')||school_can($l,$actor,'office'));school_require(in_array($c['group'],['family','teacher','student'],true)&&preg_match('/^09[0-9]{9}$/D',$c['phone']??'')===1&&!empty(trim($c['name'])));$l['contacts'][$id]=$c;}
 $l['announcements']=school_merge_rows($l['announcements'],$visible['life']['announcements'],$nl['announcements']??[],function($old,$row)use($d,&$l,$actor){school_require(!$old&&school_can($l,$actor,'announce')&&!empty(trim($row['title']))&&!empty(trim($row['body']))&&in_array($row['audience'],['all','students','staff'],true));$row['by']=$actor;$row['date']=date('Y-m-d');$targets=['admin','deputy',...array_column($l['people'],'id'),...array_map(fn($t)=>'teacher:'.$t['id'],$d['teachers']),...array_map(fn($s)=>'student:'.$s['id'],$d['students'])];foreach($targets as $to)if($to!==$actor&&($row['audience']==='all'||($row['audience']==='students')===str_starts_with($to,'student:')))school_notify($l,$to,'اطلاعیه مدرسه',$row['title'],'hub-news');return $row;});
 // Sending SMS and service credentials use a separate endpoint; snapshot writes cannot claim delivery.
 if(!school_same($nl['smsConfig']??[],$visible['life']['smsConfig'])){school_require(school_can($l,$actor,'sms'));$l['smsConfig']=['provider'=>(string)($nl['smsConfig']['provider']??''),'sender'=>(string)($nl['smsConfig']['sender']??'')];}
 foreach($nl['dispatches']??[] as $row){$old=school_find($l['dispatches'],$row['id']);if(!$old)continue;if(school_same($old,$row))continue;school_require(school_can($l,$actor,'office')&&($actor==='admin'||$old['to']===$actor));school_only($old,$row,['followups']);foreach($l['dispatches'] as &$item)if($item['id']===$old['id'])$item['followups']=$row['followups'];unset($item);}
 foreach(array_keys($changedStudents) as $id)school_notify($l,'student:'.$id,'نمره دفتر به‌روزرسانی شد','ارزشیابی تازه‌ای در دفتر کلاس ثبت شده است.','hub-grades');
 school_dispatch($d,$l,$actor);$result=['d'=>$d,'life'=>$l];school_validate($result);return $result;
}
function school_dispatch(array $d,array &$l,string $actor): void{
 foreach($d['sessions'] as $s){if(!school_course_edit($d,$actor,$s['courseId']))continue;$o=school_find($d['offerings'],$s['courseId']);$c=school_find($d['classes'],$o['classId']);$rows=[];$complete=true;foreach($d['enrollments'] as $e){if($e['classId']!==$c['id']||$e['status']!=='active')continue;$status=$s['records'][$e['studentId']]['attendance']??'unset';if($status==='unset')$complete=false;$rows[]=['id'=>$e['studentId'],'name'=>school_find($d['students'],$e['studentId'])['name'],'status'=>$status];}if(!$complete||!$rows)continue;$signature=hash('sha256',json_encode($rows));$index=null;foreach($l['dispatches'] as $i=>$x)if($x['sessionId']===$s['id']){$index=$i;break;}if($index!==null&&$l['dispatches'][$index]['signature']===$signature)continue;$to=$l['routes'][$c['id']]??$l['routes']['default']??'admin';if(!school_can($l,$to,'office'))$to='admin';$old=$index===null?null:$l['dispatches'][$index];$followups=$old['followups']??[];foreach($rows as $r)if(isset($followups[$r['id']])&&(school_find($old['rows']??[],$r['id'])['status']??null)!==$r['status'])$followups[$r['id']]['status']='open';$item=['id'=>$old['id']??school_id(),'sessionId'=>$s['id'],'yearId'=>$c['yearId'],'to'=>$to,'revision'=>($old['revision']??0)+1,'signature'=>$signature,'date'=>$s['date'],'title'=>$c['name'].' · '.$o['name'],'rows'=>$rows,'followups'=>$followups];if($index===null)$l['dispatches'][]=$item;else $l['dispatches'][$index]=$item;school_notify($l,$to,'حضور‌وغیاب آماده پیگیری است',$item['title'],'hub-followup');}
}
