import {useEffect,useRef,useState} from 'react';
import {School as SchoolIcon,Users,BookOpen,GraduationCap,Layers,ArrowUpRight,ClipboardCheck,Settings,Plus,Pencil,Download,Upload,Check,RotateCcw,ChartNoAxesCombined} from 'lucide-react';
import {SidebarProvider,Sidebar,SidebarHeader,SidebarContent,SidebarFooter,SidebarTrigger} from '@/components/ui/sidebar';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {Toaster} from '@/components/ui/sonner';import {toast} from 'sonner';
import {Choice,Field,Empty} from './widgets';import {CentralDesk} from './central-desk';import {CentralOffice} from './central-office';
import {demoSchool,schoolData,mergeTeacherData,addOffering,matches,promote,type School,type SchoolClass} from '@/lib/central-demo';
import {fa,normalize,uid,today,markLabel} from '@/lib/model';import {readExcel,exportExcel,detectSidaHeaders} from '@/lib/excel';
import './central-demo.css';
import {StudentFields} from './student-fields';
import type {LiveSchool} from '@/lib/production';
import './school-hub.css';
import {SchoolHub,hubNav,canHub} from './school-hub';
import {initialLife,accounts,allowed,syncAttendance,notify,type Dispatch,type Life,type Permission} from '@/lib/school-life';
import {JalaliDate} from './jalali-date';import {jalali,jalaliISO} from '@/lib/jalali';
const centralPermission:Record<string,Permission>={fields:'students',overview:'structure',structure:'structure',students:'students',subjects:'subjects',teachers:'teachers',assign:'assign',journal:'grades',finals:'grades',reports:'grades',office:'office',promotion:'promotion'};
const nav=[{id:'fields',name:'مشخصات دلخواه دانش‌آموز',icon:Settings},{id:'overview',name:'نمای مدرسه',icon:SchoolIcon},{id:'structure',name:'رشته، پایه و کلاس',icon:Layers},{id:'students',name:'دانش‌آموزان مدرسه',icon:Users},{id:'subjects',name:'برنامه درسی',icon:BookOpen},{id:'teachers',name:'معلمان',icon:GraduationCap},{id:'assign',name:'تخصیص تدریس',icon:ArrowUpRight},{id:'journal',name:'دفتر کلاس',icon:ClipboardCheck},{id:'finals',name:'نمرات پودمانی',icon:Check},{id:'reports',name:'کارنامه درس',icon:ChartNoAxesCombined},{id:'office',name:'غیبت و انضباط',icon:Users},{id:'promotion',name:'سال تحصیلی بعد',icon:ArrowUpRight},{id:'appearance',name:'ظاهر برنامه',icon:Settings}];
const gradeName=(d:School,id:string)=>d.grades.find(g=>g.id===id)?.name||'';
export default function CentralDemo({live}:{live?:LiveSchool}){
 const [life,setLife]=useState(()=>live?.state.life||initialLife());
 const [d,setD]=useState<School>(()=>live?.state.d||demoSchool()),[yearId,setYearId]=useState(live?.state.d.years[0]?.id||'y1'),[actor,setActor]=useState(live?.actor||'admin'),[page,setPage]=useState('hub-dashboard'),[structureTab,setStructureTab]=useState('classes'),[theme,setTheme]=useState(()=>{try{return localStorage.getItem('azarmehr-demo-theme')||'blue'}catch{return 'blue'}}),[query,setQuery]=useState(''),[classFilter,setClassFilter]=useState('all'),[majorFilter,setMajorFilter]=useState('all'),[gradeFilter,setGradeFilter]=useState('all'),[modal,setModal]=useState(''),[form,setForm]=useState<any>({}),[error,setError]=useState(''),[confirm,setConfirm]=useState<any>(null),[nextYear,setNextYear]=useState('۱۴۰۶–۱۴۰۷'),[promotionChoices,setPromotionChoices]=useState<Record<string,string>>({}),[sheets,setSheets]=useState<{name:string;rows:string[][]}[]>([]),[sheet,setSheet]=useState('0'),[header,setHeader]=useState(0),[mapping,setMapping]=useState({name:'0',father:'1',code:'2'}),[busy,setBusy]=useState(false);
 const isStudent=actor.startsWith('student:'),staff=!actor.startsWith('teacher:')&&!isStudent,teacherId=actor.startsWith('teacher:')?actor.slice(8):null,year=d.years.find(y=>y.id===yearId)!,editable=staff&&!year.archived&&allowed(life,actor,centralPermission[page]),teacher=d.teachers.find(t=>t.id===teacherId),classes=d.classes.filter(c=>c.yearId===yearId),enrollments=d.enrollments.filter(e=>e.yearId===yearId&&e.status==='active'),offers=d.offerings.filter(o=>classes.some(c=>c.id===o.classId)),selectedData=schoolData(d,yearId,teacherId);
 const classOptions=classes.map(c=>({value:c.id,label:c.name})),majorOptions=d.majors.map(m=>({value:m.id,label:m.name})),gradeOptions=d.grades.map(g=>({value:g.id,label:g.name})),filteredClasses=classes.filter(c=>(majorFilter==='all'||c.majorId===majorFilter)&&(gradeFilter==='all'||c.gradeId===gradeFilter)),filteredOffers=offers.filter(o=>(classFilter==='all'||o.classId===classFilter)&&filteredClasses.some(c=>c.id===o.classId));
 useEffect(()=>{document.body.classList.add('central-active');document.body.dataset.demoTheme=theme;try{localStorage.setItem('azarmehr-demo-theme',theme)}catch{}return()=>{document.body.classList.remove('central-active');delete document.body.dataset.demoTheme}},[theme]);
 const skipD=useRef<School|null>(null),skipL=useRef<Life|null>(null),prevSync=useRef({d,life}),deskIdle=useRef<Promise<void>>(Promise.resolve());
 useEffect(()=>{if(live){setD(live.state.d);setLife(live.state.life);setActor(live.actor);setYearId(id=>live.state.d.years.some(y=>y.id===id)?id:live.state.d.years[0].id)}},[live?.serial]);
 useEffect(()=>{if(!live)return;const dChanged=prevSync.current.d!==d,lChanged=prevSync.current.life!==life;prevSync.current={d,life};if(!dChanged&&!lChanged)return;const deskOnly=(!dChanged||skipD.current===d)&&(!lChanged||skipL.current===life);if(dChanged&&skipD.current===d)skipD.current=null;if(lChanged&&skipL.current===life)skipL.current=null;if(deskOnly)return;let cancel=false;void deskIdle.current.then(()=>{if(!cancel)live.onChange({d,life})});return()=>{cancel=true}},[d,life]);
 useEffect(()=>{if(!sheets.length)return;const h=(sheets[Number(sheet)]?.rows||[])[header]||[];if(!h.some(cell=>String(cell||'').trim()))return;const found=detectSidaHeaders(h);setMapping(current=>({name:found.name<0?current.name:String(found.name),father:found.father<0?current.father:String(found.father),code:found.code<0?current.code:String(found.code)}))},[sheets,sheet,header]);
 const change=(fn:(draft:School)=>void)=>setD(prev=>{const n=structuredClone(prev);fn(n);return n});
 const canPage=(p:string)=>p.startsWith('hub-')?canHub(life,actor,p):p==='appearance'||(!isStudent&&(teacherId?['journal','finals','reports'].includes(p):allowed(life,actor,centralPermission[p])));
 const go=(p:string)=>{if(!canPage(p))return;setPage(p);setQuery('');setError('')};
 const applyTeacher=(next:import('@/lib/model').Data)=>{if(!teacherId||year.archived)return;const n=structuredClone(d);mergeTeacherData(n,next,yearId,teacherId);setD(n);setLife(prev=>{const l=structuredClone(prev);syncAttendance(l,n,yearId,teacherId);const changed=new Set<string>();for(const session of n.sessions){const old=d.sessions.find(s=>s.id===session.id);if(session.courseId&&n.offerings.find(o=>o.id===session.courseId)?.teacherId===teacherId)for(const [id,r] of Object.entries(session.records))if(JSON.stringify(old?.records[id]?.marks||[])!==JSON.stringify(r.marks))changed.add(id)}for(const [key,f] of Object.entries(n.finals))if(JSON.stringify(d.finals[key])!==JSON.stringify(f))changed.add(key.split(':')[2]);for(const id of changed)notify(l,'student:'+id,'نمره جدید در دفتر کلاس','معلم، ارزشیابی شما را به‌روزرسانی کرده است.','hub-grades','learning');return l})};
 const applyDeskLocal=(next:import('@/lib/model').Data)=>{if(!teacherId||year.archived)return;const teacher=teacherId,yearKey=yearId;setD(prev=>{const n=structuredClone(prev);mergeTeacherData(n,next,yearKey,teacher);const ids=new Set(n.offerings.filter(o=>o.teacherId===teacher&&n.classes.some(c=>c.id===o.classId&&c.yearId===yearKey)).map(o=>o.id));for(const key of Object.keys(n.finals))if(ids.has(key.split(':')[0])&&!(key in next.finals))delete n.finals[key];skipD.current=n;return n})};
 const applyDispatch=(item:Dispatch)=>setLife(prev=>{const l=structuredClone(prev);const followups=item.followups&&!Array.isArray(item.followups)?item.followups:{};const stored={...item,followups};const i=l.dispatches.findIndex(x=>x.sessionId===item.sessionId);if(i<0)l.dispatches.push(stored);else l.dispatches[i]=stored;skipL.current=l;return l});
 const open=(name:string,value:any={})=>{setError('');setModal(name);setForm(value);if(name==='import'){setSheets([]);setHeader(0);setSheet('0')}};
 const patch=(k:string,v:any)=>setForm((f:any)=>({...f,[k]:v}));
 const reportIncident=(studentId:string,classId:string)=>open('incident',{studentId,classId,date:today(),title:'',detail:'',followup:'',status:'open'});
 function mutate(fn:(n:School)=>void){const n=structuredClone(d);fn(n);setD(n)}
 function save(){setError('');try{
  if(!editable&&modal!=='incident')throw Error('این بخش برای سال جاری و مدیر یا معاون قابل تغییر است');
  if(modal==='major'){if(!form.name?.trim())throw Error('نام رشته را وارد کنید');if(d.majors.some(x=>x.name===form.name.trim()&&x.id!==form.id))throw Error('این رشته وجود دارد');mutate(n=>{if(form.id)n.majors.find(x=>x.id===form.id)!.name=form.name.trim();else n.majors.push({id:uid(),name:form.name.trim()})})}
  if(modal==='grade'){if(!form.name?.trim()||!Number.isInteger(Number(form.order))||Number(form.order)<1)throw Error('نام و ترتیب معتبر لازم است');if(d.grades.some(x=>Number(x.order)===Number(form.order)&&x.id!==form.id))throw Error('ترتیب پایه تکراری است');mutate(n=>{const item={id:form.id||uid(),name:form.name.trim(),order:Number(form.order)};const i=n.grades.findIndex(x=>x.id===form.id);if(i<0)n.grades.push(item);else n.grades[i]=item;n.grades.sort((a,b)=>a.order-b.order)})}
  if(modal==='class'){if(!form.name?.trim()||!form.majorId||!form.gradeId||!form.section?.trim())throw Error('نام، رشته، پایه و شماره کلاس لازم است');if(classes.some(c=>c.id!==form.id&&c.majorId===form.majorId&&c.gradeId===form.gradeId&&c.section===form.section.trim()))throw Error('کلاس با این رشته، پایه و شماره وجود دارد');mutate(n=>{if(form.id){const c=n.classes.find(c=>c.id===form.id)!;c.name=form.name.trim()}else{const c:SchoolClass={id:uid(),name:form.name.trim(),section:form.section.trim(),majorId:form.majorId,gradeId:form.gradeId,yearId};n.classes.push(c);for(const s of n.subjects.filter(s=>matches(c,s)))addOffering(n,c,s)}})}
  if(modal==='student'){const existing=form.existing&&form.existing!=='new'?d.students.find(s=>s.id===form.existing):null;const code=normalize(form.code||existing?.code||''),name=normalize(form.name||existing?.name||''),father=normalize(form.father||existing?.father||''),phone=normalize(form.phone||'');if(!name||!father||!code||!form.classId)throw Error('نام، نام پدر، کد و کلاس را کامل کنید');if(phone&&!/^09\d{9}$/.test(phone))throw Error('شماره همراه دانش‌آموز معتبر نیست');for(const field of d.customFields||[])if(field.required&&!String(form.extra?.[field.id]||'').trim())throw Error(field.name+' لازم است');const id=form.id||existing?.id||uid();if(d.students.some(s=>s.code===code&&s.id!==id))throw Error('این کد قبلاً ثبت شده؛ گزینه دانش‌آموز موجود را انتخاب کنید');if(!form.id&&d.enrollments.some(e=>e.yearId===yearId&&e.studentId===id))throw Error('این دانش‌آموز در این سال ثبت‌نام شده؛ از ویرایش همان ردیف استفاده کنید');mutate(n=>{const i=n.students.findIndex(s=>s.id===id);const s={id,name,father,code,phone,extra:form.extra||{}};if(i<0)n.students.push(s);else n.students[i]=s;const e=n.enrollments.find(e=>e.studentId===id&&e.yearId===yearId);if(e)e.classId=form.classId;else n.enrollments.push({id:uid(),yearId,studentId:id,classId:form.classId,status:'active'})})}
  if(modal==='subject'){if(!form.name?.trim()||!form.gradeId||!form.majorId)throw Error('نام، پایه و رشته درس لازم است');if(form.kind==='technical'&&form.majorId==='all')throw Error('برای درس تخصصی رشته را مشخص کنید');mutate(n=>{if(form.id){const s=n.subjects.find(s=>s.id===form.id)!;s.name=form.name.trim();n.offerings.filter(o=>o.subjectId===s.id).forEach(o=>o.name=s.name)}else{const s={id:uid(),name:form.name.trim(),kind:form.kind,gradeId:form.gradeId,majorId:form.majorId};n.subjects.push(s);for(const c of n.classes.filter(c=>c.yearId===yearId&&matches(c,s)))addOffering(n,c,s)}})}
  if(modal==='teacher'){if(!form.name?.trim()||!/^\S+@\S+\.\S+$/.test(form.email||''))throw Error('نام و ایمیل معتبر وارد کنید');if(!/^09\d{9}$/.test(normalize(form.phone||'')))throw Error('شماره همراه ۱۱ رقمی معلم الزامی است');if(d.teachers.some(t=>t.email===form.email&&t.id!==form.id))throw Error('ایمیل تکراری است');mutate(n=>{const t={id:form.id||uid(),name:form.name.trim(),email:form.email,phone:normalize(form.phone),active:true};const i=n.teachers.findIndex(t=>t.id===form.id);if(i<0)n.teachers.push(t);else n.teachers[i]={...n.teachers[i],...t}})}
  if(modal==='incident'){if(year.archived)throw Error('این سال بایگانی است');if(!form.title?.trim()||!form.detail?.trim()||!form.studentId||!form.date)throw Error('دانش‌آموز، تاریخ، موضوع و شرح را وارد کنید');mutate(n=>{if(form.id){if(!staff)throw Error('پیگیری گزارش فقط با مدیر و معاون است');Object.assign(n.incidents.find(i=>i.id===form.id)!,form)}else n.incidents.push({...form,id:uid(),yearId,author:teacher?.name||'مدیریت مدرسه',followup:staff?form.followup||'':'',status:staff?form.status:'open'})})}
  setModal('');toast.success(live?'تغییر ثبت شد':'در دمو اعمال شد');
 }catch(e){setError((e as Error).message)}}
 async function safe(fn:()=>Promise<void>){setBusy(true);setError('');try{await fn()}catch(e){setError((e as Error).message);toast.error((e as Error).message)}finally{setBusy(false)}}
 const rows=(sheets[Number(sheet)]?.rows||[]),head=rows[header]||[],seen=new Set(d.students.map(s=>s.code));let duplicates=0,invalid=0;
 const importRows=rows.slice(header+1).filter(r=>r.some(Boolean)).flatMap(r=>{const extra=Object.fromEntries((d.customFields||[]).map(f=>[f.id,(()=>{const v=normalize(r[head.findIndex(h=>normalize(h)===f.name)]||'');if(f.type==='date'&&v){const p=v.split(/[/-]/).map(Number);return p[0]<1700?jalaliISO(p[0],p[1],p[2]):v}return v})()]));const name=normalize(r[Number(mapping.name)]||''),father=normalize(r[Number(mapping.father)]||''),code=normalize(r[Number(mapping.code)]||''),phone=normalize(r[head.findIndex(h=>normalize(h)==='شماره همراه')]||'');if(!name||!father||!code||(phone&&!/^09\d{9}$/.test(phone))||(d.customFields||[]).some(f=>f.required&&!extra[f.id]||f.type==='number'&&extra[f.id]&&!Number.isFinite(Number(extra[f.id])))){invalid++;return []}if(seen.has(code)){duplicates++;return []}seen.add(code);return [{name,father,code,extra,phone}]});
 const actorOptions=accounts(d,life).map(p=>({value:p.id,label:(p.roleId==='teacher'?'معلم · ':p.roleId==='student'?'دانش‌آموز · ':'')+p.name}));
 const priority=isStudent?['hub-dashboard','hub-learning','hub-grades','hub-messages','hub-notices','hub-news']:teacherId?['hub-dashboard','hub-alerts','journal','hub-learning','finals','reports','hub-messages','hub-notices','hub-news']:actor==='admin'?['hub-dashboard','hub-alerts','overview','hub-notices','hub-roles','structure','students','subjects','teachers','assign','hub-followup','hub-routing']:['hub-dashboard','hub-alerts','hub-followup','office','hub-notices','students','hub-messages','hub-routing'];
 const rank=(id:string)=>{const i=priority.indexOf(id);return i<0?100:i};
 const visibleNav=[...hubNav.filter(n=>canHub(life,actor,n.id)),...nav.filter(n=>canPage(n.id))].sort((a,b)=>rank(a.id)-rank(b.id));
 const reset=()=>setConfirm({title:'شروع دوباره دمو؟',body:'فقط تغییرات همین دمو کنار گذاشته و اطلاعات نمونه برگردانده می‌شوند.',action:()=>{setD(demoSchool());setLife(initialLife());setYearId('y1');setActor('admin');setPage('hub-dashboard');setClassFilter('all');setMajorFilter('all');setGradeFilter('all');setQuery('');setPromotionChoices({})}});
 const filters=<div className="cd-row"><Choice label="فیلتر رشته" value={majorFilter} onChange={setMajorFilter} options={[{value:'all',label:'همه رشته‌ها'},...majorOptions]}/><Choice label="فیلتر پایه" value={gradeFilter} onChange={setGradeFilter} options={[{value:'all',label:'همه پایه‌ها'},...gradeOptions]}/></div>;
 const roster=enrollments.filter(e=>classFilter==='all'||e.classId===classFilter).filter(e=>{const s=d.students.find(s=>s.id===e.studentId)!;return normalize(s.name+' '+s.code+' '+s.father).includes(normalize(query))});
 const profileStudent=modal==='profile'?d.students.find(s=>s.id===form.id):null;
 return <div className="central-demo"><SidebarProvider dir="rtl"><Toaster dir="rtl" position="top-center"/><Sidebar side="right"><SidebarHeader><div className="brand"><span className="brand-mark"><SchoolIcon/></span><div><b>دفتر کلاسی آنلاین آذرمهر</b><small>مدیریت یکپارچه هنرستان</small></div></div></SidebarHeader><SidebarContent>{visibleNav.map(n=><button key={n.id} className={'nav-item '+(page===n.id?'active':'')} onClick={()=>go(n.id)}><n.icon size={19}/>{n.name}</button>)}</SidebarContent><SidebarFooter><div className="cd-sidebar-profile"><b>{accounts(d,life).find(p=>p.id===actor)?.name}</b><small>{isStudent?'درس‌ها و فعالیت‌های من':staff?'دسترسی متناسب با سمت':'فقط درس‌های اختصاص‌یافته'}</small></div><small className="credit">طراحی: سعید آذرمهر</small></SidebarFooter></Sidebar><div className="workspace"><header className="topbar"><div className="cd-row"><SidebarTrigger/><b>هنرستان آذرمهر</b></div><div className="cd-row"><Choice label="سال تحصیلی" value={yearId} onChange={v=>{setYearId(v);setClassFilter('all');setPromotionChoices({})}} options={d.years.map(y=>({value:y.id,label:y.name+(y.archived?' · بایگانی':'')}))}/><button className="btn hub-bell" onClick={()=>go('hub-notices')} aria-label="اعلان‌های من">اعلان‌ها <b>{fa(life.notices.filter(n=>n.to===actor&&!n.read).length)}</b></button></div></header><main className="content">{!live&&<section className="cd-demo-toolbar"><div><b>پیش‌نمایش قبل از ساخت نسخه اصلی</b><p>اطلاعات نمونه و موقت‌اند؛ با بازخوانی صفحه پاک می‌شوند. اطلاعات واقعی وارد نکنید.</p></div><Choice label="مشاهده به‌عنوان" value={actor} onChange={v=>{setActor(v);go('hub-dashboard')}} options={actorOptions}/><button className="icon-btn" aria-label="شروع دوباره دمو" onClick={reset}><RotateCcw size={18}/></button></section>}{year.archived&&<div className="hint mb-5">سال بایگانی‌شده · سوابق محفوظ‌اند؛ برای ثبت اطلاعات سال جاری را انتخاب کنید.</div>}<div className="page-heading"><div><span className="cd-muted">{year.name} / {accounts(d,life).find(p=>p.id===actor)?.name}</span><h1>{[...nav,...hubNav].find(n=>n.id===page)?.name}</h1></div>{['students','subjects','teachers'].includes(page)&&editable&&<button className="btn primary" onClick={()=>open(page==='students'?'student':page==='subjects'?'subject':'teacher',page==='students'?{existing:'new',name:'',father:'',code:'',classId:classFilter==='all'?classes[0]?.id:classFilter}:page==='subjects'?{name:'',gradeId:d.grades[0]?.id,majorId:'all',kind:'general'}:{name:'',email:''})}><Plus size={18}/>{page==='students'?'ثبت دانش‌آموز':page==='subjects'?'درس جدید':'معلم جدید'}</button>}</div>
 {page.startsWith('hub-')&&<SchoolHub key={actor+':'+yearId} d={d} l={life} setLife={setLife} actor={actor} yearId={yearId} page={page} go={go} live={!!live}/>}
 {page==='fields'&&<StudentFields d={d} change={change} readonly={!editable}/>}{page==='overview'&&<div className="stack"><div className="stats">{[[enrollments.length,'دانش‌آموز یکتا'],[classes.length,'کلاس'],[offers.length,'درس در کلاس‌ها'],[d.teachers.length,'معلم']].map(([v,label])=><div className="stat" key={label}><b>{fa(v)}</b><small>{label}</small></div>)}</div><div className="cd-track-grid">{d.majors.map(m=><section className="panel cd-track" key={m.id}><span className="stat-icon color-0"><GraduationCap/></span><h2>{m.name}</h2><p>{fa(classes.filter(c=>c.majorId===m.id).length)} کلاس · {fa(enrollments.filter(e=>classes.find(c=>c.id===e.classId)?.majorId===m.id).length)} دانش‌آموز</p><div className="cd-row">{d.grades.map(g=><span className="pill" key={g.id}>{g.name}</span>)}</div><button className="btn" onClick={()=>{setMajorFilter(m.id);setGradeFilter('all');setStructureTab('classes');go('structure')}}>کلاس‌های این رشته</button></section>)}</div><section className="panel cd-setup"><h2>مدرسه یک فهرست مشترک دارد</h2><div className="cd-steps">{[['structure','۱. رشته و کلاس'],['students','۲. ثبت دانش‌آموز'],['subjects','۳. برنامه درسی'],['teachers','۴. تعریف معلم'],['assign','۵. تخصیص تدریس']].map(([p,label])=><button key={p} className="btn" onClick={()=>go(p)}>{label}</button>)}</div><p>ثبت دانش‌آموز در کلاس، او را به تمام درس‌های همان کلاس متصل می‌کند؛ ورود دوباره برای هر معلم لازم نیست.</p></section>{offers.some(o=>!o.teacherId)&&<section className="cd-notice"><div><h2>{fa(offers.filter(o=>!o.teacherId).length)} درس هنوز معلم ندارد</h2><p>تا زمان تخصیص، درس در دفتر هیچ معلمی نمایش داده نمی‌شود.</p></div><button className="btn primary" onClick={()=>{setClassFilter('all');setMajorFilter('all');setGradeFilter('all');go('assign')}}>تکمیل تخصیص‌ها</button></section>}</div>}
 {page==='structure'&&<div className="stack"><Tabs value={structureTab} onValueChange={setStructureTab} dir="rtl"><TabsList variant="line"><TabsTrigger value="classes">کلاس‌ها</TabsTrigger><TabsTrigger value="majors">رشته‌ها</TabsTrigger><TabsTrigger value="grades">پایه‌ها</TabsTrigger></TabsList></Tabs><div className="cd-row">{structureTab==='classes'&&filters}<span className="cd-grow"/>{editable&&<button className="btn primary" onClick={()=>open(structureTab==='classes'?'class':structureTab==='majors'?'major':'grade',structureTab==='classes'?{name:'',majorId:d.majors[0]?.id,gradeId:d.grades[0]?.id,section:'۲'}:structureTab==='grades'?{name:'',order:Math.max(...d.grades.map(g=>g.order))+1}:{name:''})}><Plus size={17}/>{structureTab==='classes'?'کلاس جدید':structureTab==='majors'?'رشته جدید':'پایه جدید'}</button>}</div><div className="cd-track-grid">{structureTab==='classes'?filteredClasses.map(c=><section className="panel cd-track" key={c.id}><h2>{c.name}</h2><p>{d.majors.find(m=>m.id===c.majorId)?.name} · {gradeName(d,c.gradeId)}</p><p>{fa(enrollments.filter(e=>e.classId===c.id).length)} دانش‌آموز · {fa(offers.filter(o=>o.classId===c.id).length)} درس</p><div className="cd-row"><button className="btn" onClick={()=>{setClassFilter(c.id);go('students')}}>دانش‌آموزان</button><button className="btn" onClick={()=>{setClassFilter(c.id);setMajorFilter('all');setGradeFilter('all');go('assign')}}>درس و معلم</button>{editable&&<button className="icon-btn" aria-label={'ویرایش کلاس '+c.name} onClick={()=>open('class',c)}><Pencil size={17}/></button>}</div></section>):(structureTab==='majors'?d.majors:d.grades).map(item=><section className="panel cd-track" key={item.id}><h2>{item.name}</h2>{'order'in item&&<p>ترتیب آموزشی: {fa(Number(item.order))}</p>}{editable&&<button className="btn" onClick={()=>open(structureTab==='majors'?'major':'grade',item)}>ویرایش</button>}</section>)}</div></div>}
 {page==='students'&&<section className="panel"><div className="toolbar"><input className="cd-search" aria-label="جست‌وجوی دانش‌آموزان مدرسه" value={query} onChange={e=>setQuery(e.target.value)} placeholder="نام، نام پدر یا کد…"/><Choice label="کلاس دانش‌آموزان" value={classFilter} onChange={setClassFilter} options={[{value:'all',label:'همه کلاس‌ها'},...classOptions]}/>{editable&&<button className="btn" disabled={!classes.length} onClick={()=>open('import',{classId:classFilter==='all'?classes[0]?.id:classFilter})}><Upload size={17}/> اکسل / فایل سیدا</button>}<button className="btn" onClick={()=>void safe(async()=>{await exportExcel('فهرست مدرسه',[['نام و نام خانوادگی','نام پدر','کد دانش‌آموزی','کلاس','رشته','پایه','شماره همراه',...(d.customFields||[]).map(f=>f.name)],...roster.map(e=>{const s=d.students.find(s=>s.id===e.studentId)!,c=classes.find(c=>c.id===e.classId)!;return [s.name,s.father,s.code,c.name,d.majors.find(m=>m.id===c.majorId)?.name||'',gradeName(d,c.gradeId),s.phone||'',...(d.customFields||[]).map(f=>f.type==='date'&&s.extra?.[f.id]?jalali(s.extra[f.id]):s.extra?.[f.id]||'')]})])})}><Download size={17}/> اکسل</button></div><Table><TableHeader><TableRow>{['دانش‌آموز','نام پدر','کلاس / پایه و رشته','درس‌ها','عملیات'].map(x=><TableHead key={x}>{x}</TableHead>)}</TableRow></TableHeader><TableBody>{roster.map(e=>{const s=d.students.find(s=>s.id===e.studentId)!,c=classes.find(c=>c.id===e.classId)!;return <TableRow key={e.id}><TableCell><button className="cd-student-name" onClick={()=>open('profile',{id:s.id})}>{s.name}</button><small>{s.code}</small></TableCell><TableCell>{s.father}</TableCell><TableCell>{c.name}<small>{gradeName(d,c.gradeId)} · {d.majors.find(m=>m.id===c.majorId)?.name}</small></TableCell><TableCell>{fa(offers.filter(o=>o.classId===c.id).length)} درس خودکار</TableCell><TableCell><button className="btn compact" onClick={()=>open('profile',{id:s.id})}>پرونده</button>{editable&&<button className="icon-btn" aria-label={'ویرایش دانش‌آموز '+s.name+' '+s.code} onClick={()=>open('student',{...s,classId:e.classId})}><Pencil size={16}/></button>}</TableCell></TableRow>})}</TableBody></Table>{!roster.length&&<Empty text="دانش‌آموزی با این فیلتر پیدا نشد"/>}</section>}
 {page==='subjects'&&<div className="stack">{filters}<p className="hint">درس عمومی می‌تواند به همه رشته‌های یک پایه تعلق داشته باشد؛ درس تخصصی به رشته و پایه مشخص تعلق دارد. این فهرست نمونه است و برنامه مصوب هنرستان را مدیر تنظیم می‌کند.</p><section className="panel"><Table><TableHeader><TableRow>{['درس','نوع','پایه','رشته','کلاس‌های این سال',''].map((x,i)=><TableHead key={i}>{x}</TableHead>)}</TableRow></TableHeader><TableBody>{d.subjects.filter(s=>(gradeFilter==='all'||s.gradeId===gradeFilter)&&(majorFilter==='all'||s.majorId==='all'||s.majorId===majorFilter)).map(s=><TableRow key={s.id}><TableCell>{s.name}</TableCell><TableCell><span className="pill">{s.kind==='general'?'عمومی':'تخصصی'}</span></TableCell><TableCell>{gradeName(d,s.gradeId)}</TableCell><TableCell>{s.majorId==='all'?'همه رشته‌ها':d.majors.find(m=>m.id===s.majorId)?.name}</TableCell><TableCell>{fa(offers.filter(o=>o.subjectId===s.id).length)}</TableCell><TableCell>{editable&&<button className="icon-btn" aria-label={'ویرایش درس '+s.name} onClick={()=>open('subject',s)}><Pencil size={16}/></button>}</TableCell></TableRow>)}</TableBody></Table></section></div>}
 {page==='teachers'&&<div className="cd-track-grid">{d.teachers.map(t=><section className="panel cd-track" key={t.id}><span className="avatar">{t.name[0]}</span><h2>{t.name}</h2><p dir="ltr">{t.email}</p><p>{fa(offers.filter(o=>o.teacherId===t.id).length)} درس در {fa(new Set(offers.filter(o=>o.teacherId===t.id).map(o=>o.classId)).size)} کلاس</p><button className="btn primary" onClick={()=>{setActor('teacher:'+t.id);go('journal')}}>دیدن پنل این معلم</button><div className="cd-row"><button className="btn" onClick={()=>{setClassFilter('all');setMajorFilter('all');setGradeFilter('all');go('assign')}}>تخصیص درس</button>{editable&&<button className="icon-btn" aria-label={'ویرایش معلم '+t.name} onClick={()=>open('teacher',t)}><Pencil size={17}/></button>}</div></section>)}</div>}
 {page==='assign'&&<div className="stack"><div className="cd-row">{filters}<Choice label="کلاس تخصیص" value={classFilter} onChange={setClassFilter} options={[{value:'all',label:'همه کلاس‌ها'},...classOptions]}/></div><p className="hint">هر ردیف یک درس در یک کلاس است. یک معلم می‌تواند چند ردیف داشته باشد. تغییر معلم، دانش‌آموزان و سوابق درس را جابه‌جا یا حذف نمی‌کند.</p><section className="panel"><Table><TableHeader><TableRow>{['کلاس','درس','نوع','معلم مسئول'].map(x=><TableHead key={x}>{x}</TableHead>)}</TableRow></TableHeader><TableBody>{filteredOffers.map(o=><TableRow key={o.id}><TableCell>{classes.find(c=>c.id===o.classId)?.name}</TableCell><TableCell>{o.name}</TableCell><TableCell>{d.subjects.find(s=>s.id===o.subjectId)?.kind==='general'?'عمومی':'تخصصی'}</TableCell><TableCell><Choice disabled={!editable} label={'معلم '+o.name+' '+classes.find(c=>c.id===o.classId)?.name} value={o.teacherId||'none'} onChange={v=>{change(n=>{n.offerings.find(x=>x.id===o.id)!.teacherId=v==='none'?'':v});toast.success(live?'تخصیص ثبت شد':'تخصیص در دمو اعمال شد')}} options={[{value:'none',label:'بدون معلم'},...d.teachers.filter(t=>t.active).map(t=>({value:t.id,label:t.name}))]}/></TableCell></TableRow>)}</TableBody></Table></section></div>}
 {['journal','finals','reports'].includes(page)&&<CentralDesk key={actor+':'+yearId} data={selectedData} page={page} onPage={go} readOnly={staff||year.archived} persist={!!(live&&teacherId&&!year.archived)} onChange={applyTeacher} onLocal={applyDeskLocal} onDispatch={applyDispatch} onBusy={busy=>live?.setDeskBusy?.(busy)} onQueue={ready=>{deskIdle.current=ready}} onIncident={reportIncident} audit={!!live}/>}
 {page==='office'&&staff&&<CentralOffice key={yearId} d={d} yearId={yearId} readonly={year.archived} change={change} onIncident={r=>open('incident',r)}/>}
 {page==='promotion'&&staff&&<div className="stack"><section className="panel cd-setup"><h2>ابتدا بررسی، سپس انتقال سال</h2><p>سوابق سال فعلی بایگانی می‌شوند. پیش‌فرض: دهم به یازدهم و یازدهم به دوازدهم در همان رشته. برای هر دانش‌آموز می‌توانید تکرار پایه یا عدم انتقال را انتخاب کنید. خروج از پایه آخر، تأیید رسمی فراغت از تحصیل نیست.</p><Field label="سال تحصیلی مقصد"><input disabled={!editable} value={nextYear} onChange={e=>setNextYear(e.target.value)}/></Field><p>کلاس‌ها و برنامه درسی سال مقصد ساخته می‌شوند؛ تخصیص معلم در سال جدید دوباره انجام می‌شود.</p><button className="btn primary" disabled={!editable||!enrollments.length} onClick={()=>{setError('');setConfirm({title:live?'انتقال سال تحصیلی اجرا شود؟':'اجرای انتقال فقط در دمو؟',body:'سال فعلی بایگانی و ثبت‌نام‌های سال مقصد طبق انتخاب‌های جدول ایجاد می‌شوند. نمرات و حضورهای قبلی در سال قبل باقی می‌مانند.',action:()=>{try{const n=structuredClone(d);const id=promote(n,yearId,nextYear,promotionChoices);setD(n);setYearId(id);setClassFilter('all');setPromotionChoices({});go('overview');toast.success(live?'سال جدید ساخته و سال قبلی بایگانی شد':'سال جدید در دمو ساخته شد')}catch(e){setError((e as Error).message)}}})}}>{live?'اجرای انتقال سال':'اجرای آزمایشی انتقال سال'}</button>{error&&<div className="error">{error}</div>}</section><section className="panel"><Table><TableHeader><TableRow>{['دانش‌آموز','کلاس فعلی','تصمیم','مقصد پیش‌نمایش'].map(x=><TableHead key={x}>{x}</TableHead>)}</TableRow></TableHeader><TableBody>{enrollments.map(e=>{const s=d.students.find(s=>s.id===e.studentId)!,c=classes.find(c=>c.id===e.classId)!,gs=[...d.grades].sort((a,b)=>a.order-b.order),next=gs[gs.findIndex(g=>g.id===c.gradeId)+1],mode=promotionChoices[e.id]||'advance';return <TableRow key={e.id}><TableCell>{s.name}<small>{s.code}</small></TableCell><TableCell>{c.name}</TableCell><TableCell><Choice disabled={!editable} label={'تصمیم انتقال '+s.code} value={mode} onChange={v=>setPromotionChoices(p=>({...p,[e.id]:v}))} options={[{value:'advance',label:next?'ارتقای پایه':'خروج از پایه آخر'},{value:'repeat',label:'تکرار پایه'},{value:'skip',label:'فعلاً انتقال نده'}]}/></TableCell><TableCell>{mode==='skip'?'بدون ثبت‌نام در سال مقصد':mode==='repeat'?c.name:next?next.name+' '+d.majors.find(m=>m.id===c.majorId)?.name+' / '+c.section:'خروج از دوره؛ سوابق محفوظ'}</TableCell></TableRow>})}</TableBody></Table></section></div>}
 {page==='appearance'&&<section className="panel cd-setup"><h2>ظاهر دلخواه شما</h2><p>انتخاب تم فقط ظاهر را تغییر می‌دهد و در همین مرورگر می‌ماند.</p><div className="cd-theme-grid">{[['blue','آبی روشن','سبک و شبیه ابزارهای گوگل'],['green','سبز مدرسه','روشن با تأکید سبز'],['dark','تیره','پس‌زمینه تیره با کنتراست خوانا']].map(([id,name,desc])=><button key={id} className={'cd-theme '+(theme===id?'selected':'')} aria-pressed={theme===id} onClick={()=>setTheme(id)}><span className={'cd-theme-preview '+id}><i/><i/><i/></span><b>{name}</b><p>{desc}</p>{theme===id&&<span>✓ انتخاب‌شده</span>}</button>)}</div></section>}
 </main></div><Dialog open={!!modal} onOpenChange={v=>{if(!v)setModal('')}}><DialogContent dir="rtl" className={'app-dialog cd-modal '+(['profile','import'].includes(modal)?'wide-dialog':'')}><DialogTitle>{{major:'رشته',grade:'پایه',class:'کلاس',student:'پرونده و ثبت‌نام دانش‌آموز',subject:'تعریف درس',teacher:'مشخصات معلم',profile:'پرونده یکپارچه دانش‌آموز',import:'ورود دانش‌آموزان مدرسه',incident:'گزارش انضباطی'}[modal]||''}</DialogTitle><DialogDescription>{modal==='profile'?'یک پرونده، یک ثبت‌نام در هر سال و تمام سوابق درس‌ها.':live?'تغییرات در پایگاه داده مدرسه ثبت می‌شوند.':'تغییرات این صفحه فقط در دمو اعمال می‌شوند.'}</DialogDescription>{error&&<div role="alert" className="error">{error}</div>}
 {!['profile','import'].includes(modal)&&<form className="stack" onSubmit={e=>{e.preventDefault();save()}}>
 {['major','grade','class','subject','teacher'].includes(modal)&&<Field label={modal==='teacher'?'نام و نام خانوادگی':'نام'}><input value={form.name||''} required maxLength={150} onChange={e=>patch('name',e.target.value)}/></Field>}
 {modal==='grade'&&<Field label="ترتیب پایه"><input type="number" min={1} required value={form.order} onChange={e=>patch('order',e.target.value)}/></Field>}
 {modal==='class'&&<><Field label="رشته"><Choice disabled={!!form.id} label="رشته کلاس" value={form.majorId} onChange={v=>patch('majorId',v)} options={majorOptions}/></Field><Field label="پایه"><Choice disabled={!!form.id} label="پایه کلاس" value={form.gradeId} onChange={v=>patch('gradeId',v)} options={gradeOptions}/></Field><Field label="شماره / شعبه کلاس"><input disabled={!!form.id} required value={form.section} onChange={e=>patch('section',e.target.value)}/></Field><p>رشته و پایه، مبنای برنامه درسی هستند؛ برای ترکیب متفاوت کلاس جدید بسازید.</p></>}
 {modal==='student'&&<>{!form.id&&<Field label="نوع ثبت‌نام"><Choice label="نوع ثبت‌نام" value={form.existing||'new'} onChange={v=>{const s=d.students.find(s=>s.id===v);setForm((f:any)=>({...f,existing:v,name:s?.name||'',father:s?.father||'',code:s?.code||''}))}} options={[{value:'new',label:'دانش‌آموز جدید'},...d.students.filter(s=>!d.enrollments.some(e=>e.studentId===s.id&&e.yearId===yearId)).map(s=>({value:s.id,label:s.name+' · '+s.code}))]}/></Field>}<Field label="نام و نام خانوادگی دانش‌آموز"><input required maxLength={150} value={form.name||''} onChange={e=>patch('name',e.target.value)}/></Field><Field label="شماره همراه دانش‌آموز (اختیاری)"><input inputMode="tel" value={form.phone||''} onChange={e=>patch('phone',e.target.value)}/></Field><Field label="نام پدر"><input required maxLength={100} value={form.father||''} onChange={e=>patch('father',e.target.value)}/></Field><Field label="کد دانش‌آموزی"><input required maxLength={40} value={form.code||''} onChange={e=>patch('code',e.target.value)}/></Field><Field label="کلاس مقصد"><Choice label="کلاس مقصد" value={form.classId||''} onChange={v=>patch('classId',v)} options={classOptions}/></Field>{(d.customFields||[]).map(field=><Field key={field.id} label={field.name+(field.required?' (الزامی)':'')} >{field.type==='date'?<JalaliDate value={form.extra?.[field.id]||''} onChange={v=>patch('extra',{...form.extra,[field.id]:v})} clearable={!field.required} label={field.name}/>:<input required={field.required} inputMode={field.type==='number'?'decimal':'text'} maxLength={2000} value={form.extra?.[field.id]||''} onChange={e=>patch('extra',{...form.extra,[field.id]:e.target.value})}/>}</Field>)}<p className="hint">پایه و رشته از کلاس انتخاب‌شده مشخص می‌شوند. این دانش‌آموز به تمام درس‌های همان کلاس متصل می‌شود.</p></>}
 {modal==='subject'&&<><Field label="نوع درس"><Choice disabled={!!form.id} label="نوع درس" value={form.kind} onChange={v=>{patch('kind',v);if(v==='technical'&&form.majorId==='all')patch('majorId',d.majors[0]?.id)}} options={[{value:'general',label:'عمومی'},{value:'technical',label:'تخصصی'}]}/></Field><Field label="پایه"><Choice disabled={!!form.id} label="پایه درس" value={form.gradeId} onChange={v=>patch('gradeId',v)} options={gradeOptions}/></Field><Field label="رشته"><Choice disabled={!!form.id} label="رشته درس" value={form.majorId} onChange={v=>patch('majorId',v)} options={[...(form.kind==='general'?[{value:'all',label:'همه رشته‌ها'}]:[]),...majorOptions]}/></Field><p>درس جدید به تمام کلاس‌های سازگار همین سال اضافه می‌شود. سپس معلم هر کلاس را از تخصیص تدریس انتخاب کنید.</p></>}
 {modal==='teacher'&&<><Field label="شماره همراه معلم (الزامی)"><input required inputMode="tel" value={form.phone||''} onChange={e=>patch('phone',e.target.value)}/></Field><Field label="ایمیل"><input type="email" required value={form.email||''} onChange={e=>patch('email',e.target.value)}/></Field><p>{live?'پس از ذخیره پرونده، از «حساب‌های ورود» برای معلم حساب ایجاد کنید.':'در دمو از «مشاهده به‌عنوان» پنل معلم را بررسی کنید.'}</p></>}
 {modal==='incident'&&<><h3>{d.students.find(s=>s.id===form.studentId)?.name}</h3><Field label="تاریخ"><JalaliDate value={form.date} onChange={v=>patch('date',v)} label="تاریخ گزارش"/></Field><Field label="موضوع"><input required maxLength={150} value={form.title} onChange={e=>patch('title',e.target.value)}/></Field><Field label="شرح"><textarea required maxLength={2000} value={form.detail} onChange={e=>patch('detail',e.target.value)}/></Field>{staff&&<><Field label="وضعیت رسیدگی"><Choice label="وضعیت رسیدگی" value={form.status} onChange={v=>patch('status',v)} options={[{value:'open',label:'باز'},{value:'in_progress',label:'در حال پیگیری'},{value:'resolved',label:'رسیدگی‌شده'}]}/></Field><Field label="نتیجه پیگیری"><textarea maxLength={2000} value={form.followup} onChange={e=>patch('followup',e.target.value)}/></Field></>}<p>گزارش انضباطی، نمره انضباط را تغییر نمی‌دهد.</p></>}
 <button className="btn primary" type="submit">{live?'ثبت اطلاعات':'اعمال در دمو'}</button></form>}
 {modal==='profile'&&profileStudent&&<div className="stack"><h2>{profileStudent.name}</h2><p>نام پدر: {profileStudent.father} · کد: {profileStudent.code}</p><h3>ثبت‌نام‌ها و سابقه سال تحصیلی</h3>{d.enrollments.filter(e=>e.studentId===profileStudent.id).map(e=><div className="hint" key={e.id}>{d.years.find(y=>y.id===e.yearId)?.name} · {e.status==='graduated'?'خروج از دوره':d.classes.find(c=>c.id===e.classId)?.name}</div>)}<h3>درس‌های سال انتخاب‌شده</h3>{offers.filter(o=>enrollments.some(e=>e.studentId===profileStudent.id&&e.classId===o.classId)).map(o=><div className="cd-row" key={o.id}><b>{o.name}</b><span className="cd-grow"/><span>{d.teachers.find(t=>t.id===o.teacherId)?.name||'بدون معلم'}</span></div>)}<h3>سوابق جلسات (تمام سال‌ها)</h3>{d.sessions.filter(s=>s.records[profileStudent.id]).map(s=><div className="history-row" key={s.id}><b>{jalali(s.date)} · {d.offerings.find(o=>o.id===s.courseId)?.name}</b><p>{s.title} · {({present:'حاضر',absent:'غایب',late:'تأخیر',excused:'موجه',unset:'ثبت‌نشده'} as Record<string,string>)[s.records[profileStudent.id].attendance]}</p><p>{s.records[profileStudent.id].marks.map(m=>m.type+': '+markLabel(m)).join(' · ')}</p></div>)}<button className="btn" onClick={()=>window.print()}>چاپ پرونده</button></div>}
 {modal==='import'&&<div className="stack"><p>ستون‌های کد دانش‌آموزی، نام، نام خانوادگی، نام پدر، رشته تحصیلی و پایه بدون توجه به ترتیب یا ستون خالی شناسایی می‌شوند. مشخصات دلخواه با تطبیق دقیق عنوان ستون، همراه نام پدر، کد و شماره همراه وارد می‌شوند. هر بار یک کلاس مقصد انتخاب کنید.</p><Field label="کلاس مقصد"><Choice label="کلاس ورود فایل" value={form.classId||''} onChange={v=>patch('classId',v)} options={classOptions}/></Field><input aria-label="فایل دانش‌آموزان" type="file" accept=".xlsx,.xls,.csv" onChange={e=>{const f=e.target.files?.[0];if(f)void safe(async()=>{const data=await readExcel(f);setSheets(data);setSheet('0');setHeader(0);const h=data[0]?.rows[0]||[];const found=detectSidaHeaders(h);setMapping({name:String(found.name<0?0:found.name),father:String(found.father<0?0:found.father),code:String(found.code<0?0:found.code)})})}}/>{sheets.length>0&&<><Field label="برگه"><Choice label="برگه فایل" value={sheet} onChange={setSheet} options={sheets.map((s,i)=>({value:String(i),label:s.name}))}/></Field><Field label="ردیف عنوان ستون‌ها"><input type="number" min={1} max={50} value={header+1} onChange={e=>setHeader(Math.max(0,Math.min(49,Number(e.target.value)-1)))}/></Field>{(['name','father','code'] as const).map(k=><Field key={k} label={{name:'نام و نام خانوادگی',father:'نام پدر',code:'کد دانش‌آموزی'}[k]}><Choice label={'ستون '+k} value={mapping[k]} onChange={v=>setMapping(p=>({...p,[k]:v}))} options={head.map((x,i)=>({value:String(i),label:`${i+1} · ${x||'بدون عنوان'}`}))}/></Field>)}<p>{fa(importRows.length)} قابل ورود · {fa(duplicates)} کد موجود یا تکراری · {fa(invalid)} ناقص</p><Table><TableHeader><TableRow><TableHead>نام</TableHead><TableHead>نام پدر</TableHead><TableHead>کد</TableHead></TableRow></TableHeader><TableBody>{importRows.slice(0,5).map(s=><TableRow key={s.code}><TableCell>{s.name}</TableCell><TableCell>{s.father}</TableCell><TableCell>{s.code}</TableCell></TableRow>)}</TableBody></Table><button disabled={!importRows.length||busy} className="btn primary" onClick={()=>{if(new Set(Object.values(mapping)).size!==3){setError('سه ستون متفاوت انتخاب کنید');return}if(!form.classId||importRows.length>2000){setError('کلاس لازم است و حداکثر ۲۰۰۰ دانش‌آموز در هر بار مجاز است');return}change(n=>{for(const item of importRows){const id=uid();n.students.push({...item,id});n.enrollments.push({id:uid(),yearId,studentId:id,classId:form.classId,status:'active'})}});setModal('');toast.success('فهرست مرکزی تکمیل شد')}}>ورود به کلاس انتخاب‌شده</button></>}<button className="btn" onClick={()=>void safe(async()=>{await exportExcel('الگوی ثبت‌نام مدرسه',[['نام و نام خانوادگی','نام پدر','کد دانش‌آموزی','شماره همراه',...(d.customFields||[]).map(f=>f.name)],['دانش‌آموز نمونه','علی','001234','',...(d.customFields||[]).map(()=> '')]])})}>دریافت الگوی اکسل</button></div>}
 </DialogContent></Dialog><AlertDialog open={!!confirm} onOpenChange={v=>{if(!v)setConfirm(null)}}><AlertDialogContent dir="rtl"><AlertDialogHeader><AlertDialogTitle>{confirm?.title}</AlertDialogTitle><AlertDialogDescription>{confirm?.body}</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>انصراف</AlertDialogCancel><AlertDialogAction onClick={()=>{confirm.action();setConfirm(null)}}>{live?'تأیید':'تأیید در دمو'}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></SidebarProvider></div>
}
