import {useEffect,useRef,useState} from 'react';
import {jalali} from '@/lib/jalali';
import {BookOpen,Plus,Check,Download,Shuffle,Printer} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {toast} from 'sonner';
import {Panels} from './panels';import {Modals} from './modals';import {Choice,Empty,attendance} from './widgets';
import {blankRecord,blankFinal,finalKey,totalOf,fa,normalize,today,markLabel,markTypes,pointMark,type Data,type FinalGrade} from '@/lib/model';
import {collectDeskWrites,getDeskData,saveFinalGrade,saveSessionAttendance,saveSessionMarks,withQueuedEdits} from '@/lib/production';
import {getCachedDeskData} from '@/lib/offline-db';
import {SyncStatus} from './sync-status';
import type {Dispatch} from '@/lib/school-life';
import {exportExcel,sessionRows} from '@/lib/excel';
import type {AppContext} from './context';
export function CentralDesk({data,onChange,page,onPage,readOnly,onIncident,persist,onLocal,onDispatch,onBusy,onQueue,audit}:{data:Data;onChange:(d:Data)=>void;page:string;onPage:(page:string)=>void;readOnly:boolean;onIncident:(id:string,classId:string)=>void;persist?:boolean;onLocal?:(d:Data)=>void;onDispatch?:(item:Dispatch)=>void;onBusy?:(busy:boolean)=>void;onQueue?:(ready:Promise<void>)=>void;audit?:boolean}){
 const [courseId,setCourseId]=useState(()=>data.courses.find(c=>data.sessions.some(s=>s.courseId===c.id))?.id||data.courses[0]?.id||''),[module,setModule]=useState(0),[sessionId,setSessionId]=useState(''),[tab,setTab]=useState('attendance'),[query,setQuery]=useState(''),[modal,setModal]=useState(''),[target,setTarget]=useState(''),[form,setForm]=useState<any>({}),[error,setError]=useState(''),[busy,setBusy]=useState(false),[confirm,setConfirm]=useState<any>(null);
 const course=data.courses.find(c=>c.id===courseId)||data.courses[0],classroom=data.classes.find(c=>c.id===course?.classId),sessions=data.sessions.filter(s=>s.courseId===course?.id&&s.module===module),session=sessions.find(s=>s.id===sessionId)||sessions.at(-1),allStudents=data.students.filter(s=>s.classId===course?.classId),students=allStudents.filter(s=>normalize(s.name+' '+s.code).includes(normalize(query)));
 const latest=useRef(data),sent=useRef(data),holding=useRef(false),release=useRef(()=>{}),timer=useRef(0),hooks=useRef({onChange,onLocal,onDispatch,onBusy,onQueue});
 hooks.current={onChange,onLocal,onDispatch,onBusy,onQueue};
 const flushRef=useRef<()=>Promise<void>>(async()=>{});
 useEffect(()=>{if(holding.current)return;latest.current=data;sent.current=data},[data]);
 useEffect(()=>{if(!persist||!course?.id)return;let cancel=false;const offeringId=course.id;void (async()=>{let slice=null as Awaited<ReturnType<typeof getDeskData>>|null;try{slice=await getDeskData(offeringId)}catch{try{slice=await getCachedDeskData(offeringId)}catch{slice=null}}if(!slice||cancel||holding.current)return;slice=await withQueuedEdits({...slice,offeringId:slice.offeringId||offeringId});if(cancel||holding.current)return;const next=structuredClone(latest.current);next.sessions=[...next.sessions.filter(s=>s.courseId!==offeringId),...(slice.sessions||[])];for(const key of Object.keys(next.finals))if(key.startsWith(offeringId+':'))delete next.finals[key];Object.assign(next.finals,slice.finals||{});if(JSON.stringify(next.sessions)===JSON.stringify(latest.current.sessions)&&JSON.stringify(next.finals)===JSON.stringify(latest.current.finals))return;latest.current=next;sent.current=next;hooks.current.onLocal?.(next)})().catch(()=>{});return()=>{cancel=true}},[persist,course?.id]);
 useEffect(()=>{if(!persist||!course?.id)return;const offeringId=course.id;const refresh=()=>{if(holding.current)return;void getDeskData(offeringId).then(async slice=>{if(holding.current||!slice)return;slice=await withQueuedEdits({...slice,offeringId:slice.offeringId||offeringId});if(holding.current)return;const next=structuredClone(latest.current);next.sessions=[...next.sessions.filter(s=>s.courseId!==offeringId),...(slice.sessions||[])];for(const key of Object.keys(next.finals))if(key.startsWith(offeringId+':'))delete next.finals[key];Object.assign(next.finals,slice.finals||{});latest.current=next;sent.current=next;hooks.current.onLocal?.(next)}).catch(()=>{})};window.addEventListener('pdm-synced',refresh);return()=>window.removeEventListener('pdm-synced',refresh)},[persist,course?.id]);
 function hold(){if(holding.current)return;let done=()=>{};const gate=new Promise<void>(resolve=>{done=resolve});release.current=done;holding.current=true;hooks.current.onBusy?.(true);hooks.current.onQueue?.(gate)}
 function free(){release.current();release.current=()=>{};holding.current=false;hooks.current.onBusy?.(false);hooks.current.onQueue?.(Promise.resolve())}
 async function flush(){const hook=hooks.current;try{while(true){const next=latest.current;const plan=collectDeskWrites(sent.current,next);if(!plan.attendance.length&&!plan.marks.length&&!plan.finals.length){if(plan.structural)hook.onChange(next);break}let dispatch:Dispatch|null=null,queued=false;for(const batch of plan.attendance){const res=await saveSessionAttendance(batch);if(res.queued)queued=true;else if(res.dispatch)dispatch=res.dispatch}for(const mark of plan.marks){if((await saveSessionMarks(mark)).queued)queued=true}for(const grade of plan.finals){if((await saveFinalGrade(grade)).queued)queued=true}sent.current=next;if(queued)toast.info('تغییر ذخیره شد و پس از اتصال اینترنت همگام‌سازی می‌شود.');if(plan.structural)hook.onChange(next);if(dispatch)hook.onDispatch?.(dispatch);if(latest.current===next)break}free()}catch(e){toast.error((e as Error).message);timer.current=window.setTimeout(()=>void flushRef.current(),2500)}}
 flushRef.current=flush;
 useEffect(()=>{const go=()=>{window.clearTimeout(timer.current);if(holding.current)void flushRef.current()};window.addEventListener('pagehide',go);return()=>{window.removeEventListener('pagehide',go);window.clearTimeout(timer.current)}},[]);
 function schedule(urgent:boolean){hold();window.clearTimeout(timer.current);timer.current=window.setTimeout(()=>void flushRef.current(),urgent?40:450)}
 const update=(fn:(d:Data)=>void)=>{if(readOnly){toast.info('این بخش فقط قابل مشاهده است');return}const next=structuredClone(latest.current);fn(next);latest.current=next;if(!persist){onChange(next);return}const plan=collectDeskWrites(sent.current,next);if(!plan.structural&&!plan.attendance.length&&!plan.marks.length&&!plan.finals.length)return;if(!holding.current&&plan.structural&&!plan.attendance.length&&!plan.marks.length&&!plan.finals.length){sent.current=next;onChange(next);return}(onLocal??onChange)(next);schedule(plan.urgent)};
 const record=(id:string)=>session?.records[id]||blankRecord();
 const setRecord=(id:string,patch:any)=>{if(!session)return;update(d=>{const s=d.sessions.find(s=>s.id===session.id)!;s.records[id]={...(s.records[id]||blankRecord()),...patch}})};
 function markAttendance(id:string,value:string){const previous=record(id).attendance;setRecord(id,{attendance:value});toast.success(`${data.students.find(s=>s.id===id)?.name}: ${attendance.find(a=>a.value===value)?.label}`);if(previous===value)return}
 const getFinal=(id:string,m=module)=>data.finals[finalKey(course.id,m,id)]||blankFinal();const setFinal=(id:string,patch:Partial<FinalGrade>)=>update(d=>{const key=finalKey(course.id,module,id);d.finals[key]={...(d.finals[key]||blankFinal()),...patch}});
 const open=(name:string,value:any={},id='')=>{if(name==='discipline'){onIncident(value.studentId,course.classId);setModal('');return}if(readOnly&&!['studentReport','help'].includes(name))return;setModal(name);setTarget(id);setForm(value);setError('')};
 const run=async(fn:()=>Promise<void>)=>{setBusy(true);setError('');try{await fn()}catch(e){setError((e as Error).message);toast.error((e as Error).message)}finally{setBusy(false)}};
 const exportGrades=async()=>{await exportExcel(course.name,[['نام','کد',...course.modules.map((_,i)=>`پودمان ${i+1}`)],...allStudents.map(s=>[s.name,s.code,...course.modules.map((_,i)=>totalOf(getFinal(s.id,i)))])])};
 const ctx={data,jalaliDates:true,demo:false,auth:{role:readOnly?'admin':'teacher'},role:readOnly?'admin':'teacher',staff:readOnly,readOnlyGrades:readOnly,foreign:readOnly,page,setPage:onPage,course,courseId,setCourseId,classroom,module,setModule,moduleInfo:course?.modules[module],sessions,session,sessionId,setSessionId,allStudents,students,query,setQuery,tab,setTab,record,setRecord,getFinal,setFinal,open,update,run,exportGrades,form,setForm,patchForm:(k:string,v:any)=>setForm((f:any)=>({...f,[k]:v})),modal,setModal,target,modalError:error,setModalError:setError,busy,setConfirm,classOptions:data.classes.map(c=>({value:c.id,label:c.name})),setData:onChange,downloadBackup:()=>{},classFilter:'all',setClassFilter:()=>{},audit:!!audit};
 if(!course)return <Empty text="در این سال هنوز درسی اختصاص داده نشده است" action={<p>مدیر یا معاون باید از «تخصیص تدریس»، درس و کلاس را به معلم اختصاص دهد.</p>}/>;
 return <div className="cd-desk stack">{persist&&<SyncStatus/>}<section className="class-banner"><BookOpen/><div className="course-selector"><Choice label="درس و کلاس" value={course.id} onChange={v=>{setCourseId(v);setModule(0);setSessionId('')}} options={data.courses.map(c=>({value:c.id,label:c.name+' · '+data.classes.find(x=>x.id===c.classId)?.name}))}/><p>{classroom?.grade} · {classroom?.major} · {fa(allStudents.length)} دانش‌آموز مشترک کلاس</p></div><Choice label="پودمان" value={String(module)} onChange={v=>{setModule(Number(v));setSessionId('')}} options={course.modules.map((m,i)=>({value:String(i),label:`پودمان ${fa(i+1)} · ${m.name}`}))}/></section>
 {!readOnly&&<div className="hint">با تکمیل وضعیت همه دانش‌آموزان، فهرست حضور‌وغیاب خودکار برای مسئول تعیین‌شده ارسال و اعلان ثبت می‌شود. اصلاح بعدی، همان پرونده را به‌روزرسانی می‌کند.</div>}{readOnly&&<div className="hint">نمرات فقط برای مشاهده، چاپ و گزارش در دسترس‌اند.</div>}
 {page==='journal'?<><div className="cd-row"><Choice label="جلسه" value={session?.id||''} onChange={setSessionId} options={sessions.map(s=>({value:s.id,label:new Date(s.date+'T12:00:00').toLocaleDateString('fa-IR')+' · '+s.title}))}/>{!readOnly&&<><button className="btn primary" onClick={()=>open('session',{date:today(),title:''})}><Plus size={17}/> جلسه جدید</button><button className="btn" onClick={()=>open('scales',{scales:Object.fromEntries(markTypes.filter(t=>!pointMark(t)).map(t=>[t,course.gradeScales?.[t]??20]))})}>بارم بخش‌ها</button></>}<button className="btn" onClick={()=>window.print()}><Printer size={17}/> چاپ</button><button className="btn" disabled={!session} onClick={()=>void run(async()=>{await exportExcel('دفتر جلسه',sessionRows(allStudents,session!).map((r,i)=>i?r.map((v,j)=>j===2?jalali(String(v)):v):r))})}><Download size={17}/> اکسل</button></div><Tabs value={tab} onValueChange={setTab} dir="rtl"><TabsList variant="line"><TabsTrigger value="attendance">حضور‌وغیاب یک‌لمسی</TabsTrigger><TabsTrigger value="grades">نمره و ارزشیابی</TabsTrigger></TabsList></Tabs>
 <div className="cd-row"><input className="cd-search" aria-label="جست‌وجوی کلاس" value={query} onChange={e=>setQuery(e.target.value)} placeholder="نام یا کد دانش‌آموز…"/><span className="cd-grow"/><span className="cd-muted">{fa(allStudents.filter(s=>record(s.id).attendance==='unset').length)} ثبت‌نشده</span>{!readOnly&&<><button disabled={!session} className="btn" onClick={()=>update(d=>{const s=d.sessions.find(s=>s.id===session!.id)!;for(const p of allStudents)if(!s.records[p.id]||s.records[p.id].attendance==='unset')s.records[p.id]={...(s.records[p.id]||blankRecord()),attendance:'present'}})}><Check size={17}/> ثبت‌نشده‌ها حاضر</button><button disabled={!session} className="btn" onClick={()=>open('picker')}><Shuffle size={17}/> انتخاب برای پرسش</button></>}</div>
 {!session?<Empty text="برای این پودمان جلسه‌ای ثبت نشده است"/>:!students.length?<Empty text="دانش‌آموزی در این کلاس نیست"/>:<div className="cd-attendance-grid">{students.map((s,i)=>{const r=record(s.id);return <article className="panel cd-person" key={s.id}><div className="cd-row"><span className={'avatar color-'+i%4}>{s.name[0]}</span><div className="cd-grow"><button className="cd-student-name" onClick={()=>open('studentReport',{},s.id)}>{s.name}</button><small>{s.code}</small></div><span className={'pill '+r.attendance}>{attendance.find(a=>a.value===r.attendance)?.label}</span></div>{tab==='attendance'?<div className="cd-attendance" role="group" aria-label={'حضور '+s.name}>{attendance.filter(a=>a.value!=='unset').map(a=><button key={a.value} disabled={readOnly} aria-pressed={r.attendance===a.value} className={'cd-attendance-button '+a.value} onClick={()=>markAttendance(s.id,a.value)}>{a.value==='excused'?'موجه':a.label}</button>)}</div>:<><div className="marks">{r.marks.length?r.marks.map(m=><button disabled={readOnly} className="mark-chip" key={m.id} onClick={()=>open('grade',{...m,value:String(m.value),studentId:s.id},m.id)}>{m.type} · {markLabel(m)}</button>):<p>هنوز ارزشیابی ندارد</p>}</div>{!readOnly&&<button className="btn" onClick={()=>open('grade',{studentId:s.id,type:'کارگاهی',value:'',max:course.gradeScales?.['کارگاهی']??20,note:'',competency:1})}><Plus size={16}/> ثبت نمره</button>}</>}
 <input disabled={readOnly} aria-label={'یادداشت '+s.name} value={r.note} maxLength={2000} onChange={e=>setRecord(s.id,{note:e.target.value})} className="cd-note" placeholder="یادداشت جلسه…"/>{!readOnly&&<button className="text-link" onClick={()=>onIncident(s.id,course.classId)}>گزارش انضباطی</button>}</article>})}</div>}</>:<Panels ctx={ctx as AppContext}/>}
 <Modals ctx={ctx as AppContext}/><AlertDialog open={!!confirm} onOpenChange={v=>{if(!v)setConfirm(null)}}><AlertDialogContent dir="rtl"><AlertDialogHeader><AlertDialogTitle>{confirm?.title}</AlertDialogTitle><AlertDialogDescription>{confirm?.body}</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>انصراف</AlertDialogCancel><AlertDialogAction onClick={()=>{confirm.action();setConfirm(null)}}>تأیید</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </div>
}
