import {useEffect,useState} from 'react';
import {Users,Plus,Pencil,BookOpen,RefreshCw,ShieldCheck} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Switch} from '@/components/ui/switch';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
import {Choice,Field} from './widgets';
import {api} from '@/lib/api';
import {fa} from '@/lib/model';
import {toast} from 'sonner';
export const roleNames:Record<string,string>={admin:'مدیر',deputy:'معاون / ناظم',teacher:'معلم'};
type Account={id:number;name:string;email:string;role:string;active:boolean;revision:number;classes:number;students:number;courses:number;sessions:number};
export function Management({demo,auth,onOpen}:{demo:boolean;auth:any;onOpen:(id:number,page?:string)=>Promise<void>}){
 const [accounts,setAccounts]=useState<Account[]>([]),[events,setEvents]=useState<any[]>([]),[error,setError]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[query,setQuery]=useState(''),[form,setForm]=useState<any>(null),[showAudit,setShowAudit]=useState(false);
 async function refresh(){setLoading(true);setError('');try{if(demo){setAccounts([{id:1,name:'سعید آذرمهر',email:'admin@example.test',role:'admin',active:true,revision:0,classes:1,students:12,courses:1,sessions:1},{id:2,name:'معاون نمونه',email:'deputy@example.test',role:'deputy',active:true,revision:0,classes:0,students:0,courses:0,sessions:0},{id:3,name:'معلم نمونه',email:'teacher@example.test',role:'teacher',active:true,revision:0,classes:1,students:12,courses:1,sessions:1}]);return}const r=await api('staff_list',{});setAccounts(r.accounts)}catch(e){setError((e as Error).message)}finally{setLoading(false)}}
 useEffect(()=>{void refresh()},[]);
 const admin=auth?.role==='admin';
 const patch=(k:string,v:unknown)=>setForm((f:any)=>({...f,[k]:v}));
 async function save(){setBusy(true);setError('');try{if(demo){toast.info('ایجاد و ویرایش حساب واقعی پس از نصب روی هاست فعال است');return}await api(form.id?'staff_update':'create_teacher',{...form,userId:form.id});setForm(null);await refresh();toast.success('اطلاعات حساب ذخیره شد')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <div className="stack"><div className="management-intro"><ShieldCheck size={26}/><div><h2>مدیریت مدرسه</h2><p>حساب همکاران را مدیریت کنید و دفتر هر معلم را برای سامان‌دهی دانش‌آموزان و مشاهده عملکرد باز کنید.</p></div><button className="btn primary" onClick={()=>{setError('');setForm({name:'',email:'',password:'',role:'teacher',active:true})}}><Plus size={17}/> همکار جدید</button></div>
 <div className="stats">{[[accounts.filter(a=>a.active&&a.role==='teacher').length,'معلم فعال'],[accounts.reduce((n,a)=>n+a.classes,0),'کلاس در دفترها'],[accounts.reduce((n,a)=>n+a.students,0),'ثبت دانش‌آموز در دفترها'],[accounts.reduce((n,a)=>n+a.sessions,0),'جلسه ثبت‌شده']].map(([v,label])=><section className="stat" key={label}><span className="stat-icon color-0"><Users size={20}/></span><div><b>{fa(v)}</b><small>{label}</small></div></section>)}</div>
 <p className="hint">دانش‌آموز مشترک در چند دفتر، در شمارش بالا چند بار حساب می‌شود. برای تعریف یا ورود فهرست دانش‌آموزان، ابتدا دفتر معلم مقصد را باز کنید. نمرات دفتر دیگران فقط قابل مشاهده‌اند.</p>
 {error&&!form&&<div role="alert" className="error">{error}</div>}
 <section className="panel management-panel"><div className="toolbar"><input aria-label="جست‌وجوی همکار" value={query} onChange={e=>setQuery(e.target.value)} placeholder="نام یا ایمیل همکار…"/><button disabled={loading} className="btn" onClick={()=>void refresh()}><RefreshCw size={16}/> تازه‌سازی</button><button className="btn" onClick={async()=>{setShowAudit(!showAudit);if(!showAudit&&!demo)try{const r=await api('staff_audit',{});setEvents(r.events)}catch(e){setError((e as Error).message)}}}>سوابق مدیریت</button></div>
 {loading?<p className="p-6" role="status">در حال دریافت حساب‌ها…</p>:<Table><TableHeader><TableRow>{['همکار','نقش','وضعیت','دانش‌آموز / درس','دسترسی'].map(x=><TableHead key={x}>{x}</TableHead>)}</TableRow></TableHeader><TableBody>{accounts.filter(a=>(a.name+' '+a.email).toLowerCase().includes(query.toLowerCase())).map(a=><TableRow key={a.id}><TableCell><b>{a.name}</b><small dir="ltr">{a.email}</small></TableCell><TableCell>{roleNames[a.role]}</TableCell><TableCell><span className={'pill '+(a.active?'present':'absent')}>{a.active?'فعال':'غیرفعال'}</span></TableCell><TableCell>{fa(a.students)} / {fa(a.courses)}</TableCell><TableCell><div className="flex gap-2 flex-wrap"><button className="btn compact" onClick={()=>void onOpen(a.id,'students')}><Users size={15}/> دانش‌آموزان</button><button className="btn compact" onClick={()=>void onOpen(a.id,'reports')}><BookOpen size={15}/> مشاهده دفتر</button>{a.id!==(auth?.id??1)&&(admin||a.role==='teacher')&&<button className="icon-btn" aria-label={'ویرایش حساب '+a.name} onClick={()=>{setError('');setForm({...a})}}><Pencil size={17}/></button>}</div></TableCell></TableRow>)}</TableBody></Table>}
 {!loading&&!accounts.length&&!error&&<p className="p-6">حسابی ثبت نشده است.</p>}</section>
 {showAudit&&<section className="panel p-6 stack"><h2>۱۰۰ تغییر مدیریتی اخیر</h2><p>ثبت خودکار تغییر حساب‌ها و مدیریت فهرست‌ها؛ رمز عبور در این سوابق ثبت نمی‌شود.</p>{events.length?<Table><TableHeader><TableRow>{['زمان سرور','انجام‌دهنده','حساب مقصد','عملیات'].map(x=><TableHead key={x}>{x}</TableHead>)}</TableRow></TableHeader><TableBody>{events.map(e=><TableRow key={e.id}><TableCell>{e.created_at}</TableCell><TableCell>{e.actor}</TableCell><TableCell>{e.target}</TableCell><TableCell>{({account_create:'ایجاد حساب',account_update:'ویرایش حساب',roster_update:'ویرایش فهرست کلاس و دانش‌آموز',attendance_update:'اصلاح حضور و پیگیری',incident_create:'ثبت گزارش انضباطی',incident_update:'پیگیری گزارش انضباطی'} as Record<string,string>)[e.action]||e.action}</TableCell></TableRow>)}</TableBody></Table>:<p>هنوز تغییری ثبت نشده است.</p>}</section>}
 <Dialog open={Boolean(form)} onOpenChange={v=>{if(!v&&!busy)setForm(null)}}><DialogContent dir="rtl"><DialogTitle>{form?.id?'ویرایش حساب همکار':'همکار جدید'}</DialogTitle><DialogDescription>هر معلم دفتر مستقل دارد. مدیر و معاون امکان مشاهده دفترها را دارند.</DialogDescription>{form&&<form className="stack" onSubmit={e=>{e.preventDefault();void save()}}>{error&&<div role="alert" className="error">{error}</div>}<Field label="نام و نام خانوادگی"><input required maxLength={100} value={form.name} onChange={e=>patch('name',e.target.value)}/></Field><Field label="ایمیل ورود"><input required type="email" dir="ltr" maxLength={190} value={form.email} onChange={e=>patch('email',e.target.value)}/></Field><Field label="نقش"><Choice label="نقش همکار" value={form.role} onChange={v=>patch('role',v)} options={Object.entries(roleNames).filter(([key])=>admin||key==='teacher').map(([value,label])=>({value,label}))}/></Field>{!form.id&&<Field label="رمز اولیه (حداقل ۱۲ نویسه)"><input type="password" required minLength={12} autoComplete="new-password" value={form.password} onChange={e=>patch('password',e.target.value)}/></Field>}<div className="flex items-center gap-3"><Switch id="account-active" checked={form.active} onCheckedChange={v=>patch('active',v)}/><label htmlFor="account-active">حساب فعال باشد</label></div><p className="hint">غیرفعال‌کردن، ورود و نشست‌های قبلی را متوقف می‌کند و سوابق را نگه می‌دارد. ویرایش حساب، همکار را ملزم به ورود دوباره می‌کند.</p><button disabled={busy} className="btn primary">{busy?'در حال ذخیره…':'ذخیره حساب'}</button></form>}</DialogContent></Dialog></div>
}
