import type {AppContext} from './context';
import {useEffect,useState,FormEvent} from 'react';
import {Download,Shuffle,Trash2,Printer} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
import {toast} from 'sonner';
import {fa,uid,normalize,defaultFormula,markTypes,performance,evaluate,finalKey,blankFinal,totalOf,pointMark,markLabel,markOutOf20,today} from '@/lib/model';
import {jalali} from '@/lib/jalali';
import {readExcel,exportExcel,detectSidaHeaders} from '@/lib/excel';
import {GradeAudit} from './grade-audit';
import {Choice,Field,attendance} from './widgets';
import {JalaliDate} from './jalali-date';
export function Modals({ctx:a}:{ctx:AppContext}){
 const {data,modal,setModal,target,form,patchForm,modalError,setModalError,busy,run,update,course,module,moduleInfo,session,sessions,allStudents,record,setRecord,classOptions,setConfirm,open,getFinal,classroom}=a;
 const [sheets,setSheets]=useState<{name:string;rows:string[][]}[]>([]),[sheetIndex,setSheetIndex]=useState(0),[headerRow,setHeaderRow]=useState(0),[mapping,setMapping]=useState({name:'0',last:'none',code:'1'}),[picked,setPicked]=useState(''),[pickMode,setPickMode]=useState('unasked');
 useEffect(()=>{setPicked('');if(modal==='import'){setSheets([]);setSheetIndex(0);setHeaderRow(0)}},[modal]);
 useEffect(()=>{const h=sheets[sheetIndex]?.rows[headerRow]||[];if(!h.some(cell=>String(cell).trim()))return;const found=detectSidaHeaders(h);setMapping(current=>({name:found.name<0?current.name:String(found.name),last:found.last<0?current.last:String(found.last),code:found.code<0?current.code:String(found.code)}))},[sheets,sheetIndex,headerRow]);
 const saveForm=(event:FormEvent)=>{event.preventDefault();void run(async()=>{
 if(modal==='class'){if(!form.name?.trim())throw Error('نام کلاس را وارد کنید');update(d=>{const item={id:target||uid(),name:form.name.trim(),grade:form.grade||'دهم',major:form.major||'',year:form.year||d.profile.year};const i=d.classes.findIndex(c=>c.id===target);i<0?d.classes.push(item):d.classes.splice(i,1,item)})}
 if(modal==='course'){if(!form.name?.trim()||!form.classId||form.modules.some(m=>!m.name.trim()))throw Error('نام درس، پودمان‌ها و کلاس لازم است');if(target){const previous=data.courses.find(c=>c.id===target)!;for(let i=0;i<5;i++)if(previous.modules[i].competencies===2&&form.modules[i].competencies===1){const hasEvidence=data.sessions.some(s=>s.courseId===target&&s.module===i&&Object.values(s.records).some((r:any)=>r.marks.some((m:any)=>m.competency===2)))||Object.entries(data.finals).some(([key,f]:any)=>key.startsWith(target+':'+i+':')&&f.competencies[1]!=null);if(hasEvidence)throw Error('برای شایستگی دوم پودمان '+fa(i+1)+' نمره ثبت شده؛ تعداد را کاهش ندهید')}}update(d=>{if(target){const c=d.courses.find(c=>c.id===target)!;c.name=form.name.trim();c.modules=form.modules}else{const id=uid();d.courses.push({id,name:form.name.trim(),classId:form.classId,modules:form.modules,formula:{...defaultFormula}});a.setCourseId(id);a.setModule(0)}})}
 if(modal==='student'){const name=normalize(form.name||''),code=normalize(form.code||'');if(!name||!code||!form.classId)throw Error('نام، کد و کلاس لازم است');if(data.students.some(s=>s.code===code&&s.id!==target))throw Error('این کد دانش‌آموزی قبلاً ثبت شده است');update(d=>{const s={id:target||uid(),name,code,classId:form.classId};const i=d.students.findIndex(x=>x.id===target);i<0?d.students.push(s):d.students.splice(i,1,s)})}
 if(modal==='session'){if(!course||!form.date||!form.title?.trim())throw Error('تاریخ و عنوان جلسه را وارد کنید');if(form.id||target){const sid=form.id||target;update(d=>{const s=d.sessions.find(x=>x.id===sid);if(!s)throw Error('جلسه پیدا نشد');s.title=form.title.trim();s.date=form.date});a.setSessionId(sid)}else{const id=uid();update(d=>d.sessions.push({id,courseId:course.id,module,date:form.date,title:form.title.trim(),records:{}}));a.setSessionId(id)}}
 if(modal==='grade'){const value=Number(normalize(form.value||'')),max=Number(normalize(String(form.max??20)).replace('٫','.'));if(!Number.isFinite(max)||max<.01||max>1000)throw Error('بارم باید بیشتر از صفر و حداکثر ۱۰۰۰ باشد');if(!String(form.value??'').trim()||!Number.isFinite(value)||value<0||value>(pointMark(form.type)?1000:max))throw Error('نمره باید بین صفر و بارم انتخابی باشد');const entry={id:target||uid(),type:form.type,value,max,note:form.note||'',competency:Number(form.competency||1)};const old=record(form.studentId);setRecord(form.studentId,{marks:target?old.marks.map(m=>m.id===target?entry:m):[...old.marks,entry],asked:old.asked||form.type==='پرسش شفاهی'||form.type==='پرسش کتبی'})}
 if(modal==='scales'){const scales:Record<string,number>={};for(const t of markTypes.filter(t=>!pointMark(t))){const n=Number(normalize(String(form.scales[t])).replace('٫','.'));if(!Number.isFinite(n)||n<.01||n>1000)throw Error('بارم هر بخش بیشتر از صفر و حداکثر ۱۰۰۰ باشد');scales[t]=n}update(d=>{d.courses.find(c=>c.id===course.id)!.gradeScales=scales})}
 if(modal==='formula'){
const formula={expression:form.expression,minimum:Number(form.minimum),high:Number(form.high),round:Number(form.round),pass:Number(form.pass)};evaluate(formula.expression,{avg:16,workshop:17,oral:14,written:15,classwork:15,discipline:18,presentation:18,homework:16,count:4,positive:1,negative:0,attendance:90});if(!(formula.minimum>=0&&formula.minimum<=formula.high&&formula.high<=20&&formula.pass>=0&&formula.pass<=20&&[.5,1].includes(formula.round)))throw Error('حدود فرمول معتبر نیست');update(d=>{d.courses.find(c=>c.id===course.id)!.formula=formula})}
 setModal('');})};
 function chooseStudent(){if(!course||!session)return;const eligible=allStudents.filter(s=>!['absent','excused','unset'].includes(record(s.id).attendance)).filter(s=>{const p=performance(data,course.id,module,s.id);return pickMode==='all'||pickMode==='unasked'&&!p.asked||pickMode==='ungraded'&&!p.scored.length});if(!eligible.length){setPicked('');toast.info('دانش‌آموز واجد شرایطی نیست؛ حضور یا فیلتر را بررسی کنید');return}const random=new Uint32Array(1);crypto.getRandomValues(random);setPicked(eligible[Math.floor(random[0]/4294967296*eligible.length)].id)}
 const header=sheets[sheetIndex]?.rows[headerRow]||[],importRows=sheets[sheetIndex]?.rows.slice(headerRow+1).filter(r=>r.some(v=>String(v).trim()))||[];
 const importCandidates=importRows.map((r,i)=>({row:headerRow+i+2,name:normalize(String(r[Number(mapping.name)]||'')+' '+(mapping.last==='none'?'':String(r[Number(mapping.last)]||''))),code:normalize(String(r[Number(mapping.code)]||''))}));
 const seen=new Set(data.students.map(s=>s.code));let duplicateCount=0,invalidCount=0;const importValid=importCandidates.filter(s=>{if(!s.name||!s.code||s.name.length>150||s.code.length>40){invalidCount++;return false}if(seen.has(s.code)){duplicateCount++;return false}seen.add(s.code);return true});
 return <Dialog open={Boolean(modal)} onOpenChange={v=>{if(!v)setModal('')}}><DialogContent dir="rtl" className={'app-dialog '+(['import','studentReport','suggestions'].includes(modal)?'wide-dialog':'')}><DialogTitle>{(({class:target?'ویرایش کلاس':'کلاس جدید',course:target?'ویرایش درس':'درس جدید',student:target?'ویرایش دانش‌آموز':'دانش‌آموز جدید',session:(form.id||target)?'ویرایش جلسه':'جلسه جدید',grade:'ثبت ارزشیابی',scales:'بارم پیش‌فرض بخش‌ها',picker:'چه کسی پاسخ بدهد؟',import:'ورود دانش‌آموزان از اکسل یا سیدا',formula:'فرمول پیشنهاد نمره',suggestions:'پیشنهاد نمره؛ بررسی پیش از ثبت',studentReport:'کارنامه و سابقه دانش‌آموز',help:'راهنمای سریع دفتر'}) as Record<string,string>)[modal]||''}</DialogTitle><DialogDescription>{modal==='picker'?'انتخاب از میان حاضران و افراد دارای تأخیر در همین جلسه.':modal==='import'?'فایل خروجی را انتخاب کنید؛ ستون‌ها و پیش‌نمایش را بررسی کنید.':modal==='suggestions'?'این پیشنهاد محاسباتی است، نه ارزیابی قطعی مهارت. نمرات قبلی بازنویسی نمی‌شوند.':'اطلاعات را در بخش‌های زیر وارد یا بررسی کنید.'}</DialogDescription>{modalError&&<div className="error">{modalError}</div>}
 {['class','course','student','session','grade','formula','scales'].includes(modal)&&<form className="stack" onSubmit={saveForm}>
 {modal==='class'&&<><Field label="نام کلاس"><input required maxLength={100} value={form.name||''} onChange={e=>patchForm('name',e.target.value)}/></Field><div className="form-grid"><Field label="پایه"><Choice label="پایه" value={form.grade} onChange={v=>patchForm('grade',v)} options={['دهم','یازدهم','دوازدهم','سایر'].map(v=>({value:v,label:v}))}/></Field><Field label="سال تحصیلی"><input maxLength={30} value={form.year||''} onChange={e=>patchForm('year',e.target.value)}/></Field></div><Field label="رشته"><input maxLength={150} value={form.major||''} onChange={e=>patchForm('major',e.target.value)}/></Field></>}
 {modal==='course'&&<><Field label="عنوان درس"><input required maxLength={150} value={form.name||''} onChange={e=>patchForm('name',e.target.value)}/></Field><Field label="کلاس"><Choice disabled={Boolean(target)} label="کلاس" value={form.classId} onChange={v=>patchForm('classId',v)} options={classOptions}/></Field>{form.modules?.map((m,i)=><div className="module-edit" key={i}><span>{fa(i+1)}</span><input aria-label={'عنوان پودمان '+fa(i+1)} value={m.name} maxLength={150} required onChange={e=>patchForm('modules',form.modules.map((x,n)=>n===i?{...x,name:e.target.value}:x))}/><Choice label="تعداد شایستگی" value={String(m.competencies)} onChange={v=>patchForm('modules',form.modules.map((x,n)=>n===i?{...x,competencies:Number(v)}:x))} options={[{value:'1',label:'۱ شایستگی'},{value:'2',label:'۲ شایستگی'}]}/></div>)}</>}
 {modal==='student'&&<><Field label="نام و نام خانوادگی"><input required maxLength={150} value={form.name||''} onChange={e=>patchForm('name',e.target.value)}/></Field><Field label="کد دانش‌آموزی (صفر ابتدایی حفظ می‌شود)"><input required value={form.code||''} onChange={e=>patchForm('code',e.target.value)} maxLength={40}/></Field><Field label="کلاس"><Choice label="کلاس" value={form.classId} onChange={v=>patchForm('classId',v)} options={classOptions}/></Field>{target&&<p className="hint">با تغییر کلاس، سوابق قبلی حذف نمی‌شوند. در دفتر کلاس قبلی، همان جلسه جدا از فهرست حضور فعلی دیده می‌شود. برای تحویل به دفتر، کارنامه را هم بگیرید.</p>}</>}
 {modal==='session'&&<><Field label="عنوان جلسه"><input required maxLength={150} placeholder="مثلاً: تمرین الگوریتم و حل مسئله" value={form.title||''} onChange={e=>patchForm('title',e.target.value)}/></Field><Field label={a.jalaliDates?'تاریخ جلسه (شمسی)':'تاریخ جلسه (تقویم دستگاه؛ نمایش در دفتر شمسی است)'}>{a.jalaliDates?<JalaliDate value={form.date} onChange={v=>patchForm('date',v)} label="تاریخ جلسه"/>:<input required type="date" value={form.date} onChange={e=>patchForm('date',e.target.value)}/>}</Field><p className="hint">{course?.name} · پودمان {fa(module+1)}<br/>{(form.id||target)?'فقط عنوان و تاریخ جلسه تغییر می‌کند؛ حضور و نمرات حفظ می‌شوند.':'وضعیت اولیه همه دانش‌آموزان «ثبت نشده» خواهد بود.'}</p></>}
 {modal==='grade'&&<><p>{data.students.find(s=>s.id===form.studentId)?.name}</p>{a.audit&&course&&form.studentId&&<GradeAudit offeringId={course.id} studentId={form.studentId} moduleIndex={module} name={data.students.find(s=>s.id===form.studentId)?.name}/>}<div className="form-grid"><Field label="نوع ارزشیابی"><Choice label="نوع نمره" value={form.type} onChange={v=>{patchForm('type',v);if(!target)patchForm('max',course.gradeScales?.[v]??20)}} options={markTypes.map(v=>({value:v,label:v}))}/></Field><Field label={pointMark(form.type)?'تعداد امتیاز (حداکثر ۱۰۰۰)':'نمره کسب‌شده'}><input required inputMode="decimal" value={form.value??''} onChange={e=>patchForm('value',normalize(e.target.value).replace('٫','.'))}/></Field></div>{!pointMark(form.type)&&<><Field label="بارم این ارزشیابی (از چند؟)"><input required inputMode="decimal" value={form.max??20} onChange={e=>patchForm('max',normalize(e.target.value).replace('٫','.'))}/></Field><div className="flex gap-2">{[5,10,20,100].map(v=><button type="button" key={v} className="btn compact" onClick={()=>patchForm('max',v)}>از {fa(v)}</button>)}</div><p className="hint">نمره با بارم اصلی ذخیره می‌شود. میانگین و پیشنهاد نمره، معادل از ۲۰ را با وزن برابر هر ارزشیابی محاسبه می‌کنند.</p></>}<Field label="شایستگی مربوط"><Choice label="شایستگی" value={String(form.competency||1)} onChange={v=>patchForm('competency',v)} options={Array.from({length:moduleInfo?.competencies||1},(_,i)=>({value:String(i+1),label:`شایستگی ${fa(i+1)}`}))}/></Field><Field label="توضیحات ارزشیابی"><textarea value={form.note||''} onChange={e=>patchForm('note',e.target.value)} maxLength={2000} placeholder="موضوع پرسش، تمرین یا بازخورد…"/></Field>{target&&<button type="button" className="btn danger" onClick={()=>setConfirm({title:'حذف این ارزشیابی؟',body:'فقط همین نمره از جلسه حذف می‌شود.',action:()=>{setRecord(form.studentId,{marks:record(form.studentId).marks.filter(m=>m.id!==target)});setModal('')}})}><Trash2 size={16}/> حذف ارزشیابی</button>}</>}
 {modal==='formula'&&<><Field label="فرمول نمره مستمر (محدود به صفر تا ۵)"><textarea dir="ltr" required value={form.expression} onChange={e=>patchForm('expression',e.target.value)} maxLength={300}/></Field><p className="hint">avg: میانگین نمره‌ها · workshop: کارگاهی · oral: شفاهی · written: کتبی · classwork: سرکلاسی · discipline: انضباط · presentation: ارائه · homework: تکلیف · positive / negative: مجموع امتیاز · attendance: درصد حضور · count: تعداد نمره<br/>مثال: <code dir="ltr">if(count &gt;= 3, avg / 4, min(avg / 4, 3))</code><br/>توابع: min، max، round و if. میانگین avg وزن برابر دارد و بارم بزرگ‌تر به‌تنهایی رأی بیشتری نمی‌گیرد. if فقط شاخهٔ انتخاب‌شده را حساب می‌کند. دسته بدون نمره در فرمول صفر است؛ نبود همه نمره‌ها پیشنهاد تولید نمی‌کند.</p><div className="form-grid"><Field label="حداقل میانگین کارگاهی برای شایستگی ۲"><input type="number" min="0" max="20" value={form.minimum} onChange={e=>patchForm('minimum',e.target.value)}/></Field><Field label="حداقل میانگین کارگاهی برای شایستگی ۳"><input type="number" min="0" max="20" value={form.high} onChange={e=>patchForm('high',e.target.value)}/></Field><Field label="گام گرد کردن مستمر"><Choice label="گرد کردن" value={String(form.round)} onChange={v=>patchForm('round',v)} options={[{value:'0.5',label:'نیم نمره'},{value:'1',label:'یک نمره'}]}/></Field><Field label="حداقل نمره پودمان برای گزارش قبولی"><input type="number" min="0" max="20" value={form.pass} onChange={e=>patchForm('pass',e.target.value)}/></Field></div><p>پیشنهاد شایستگی از نمرات کارگاهی همان شایستگی محاسبه می‌شود. پیشنهاد نهایی برابر کمترین شایستگی است و باید توسط معلم بررسی شود.</p></>}
 {modal==='scales'&&<><p>بارم پیش‌فرض هر بخش در این درس را تعیین کنید. بارم نمرات قبلی تغییر نمی‌کند و هنگام ثبت هر نمره هم قابل انتخاب است.</p><div className="form-grid">{markTypes.filter(t=>!pointMark(t)).map(t=><Field key={t} label={t+' از چند؟'}><input required inputMode="decimal" value={form.scales?.[t]??20} onChange={e=>patchForm('scales',{...form.scales,[t]:normalize(e.target.value).replace('٫','.')})}/></Field>)}</div></>}
 <button className="btn primary" disabled={busy} type="submit">{busy?'در حال انجام…':modal==='grade'?'ثبت ارزشیابی':(form.id||target)&&modal==='session'?'اعمال تغییرات':target?'اعمال تغییرات':'ثبت'}</button></form>}
 {modal==='picker'&&<div className="stack"><Choice label="روش انتخاب" value={pickMode} onChange={v=>{setPickMode(v);setPicked('')}} options={[{value:'unasked',label:'پرسیده‌نشده‌ها در این پودمان'},{value:'ungraded',label:'بدون نمره در این پودمان'},{value:'all',label:'تصادفی از همه حاضران'}]}/><div className="picked"><Shuffle size={30}/><h2>{data.students.find(s=>s.id===picked)?.name||'نوبت چه کسی است؟'}</h2><p>{picked?'انتخاب شدن، به‌تنهایی به معنی پرسیده شدن نیست.':'با یک لمس، انتخاب منصفانه انجام دهید.'}</p></div><button className="btn primary" onClick={chooseStudent}><Shuffle size={17}/> {picked?'انتخاب دوباره':'انتخاب دانش‌آموز'}</button>{picked&&<div className="flex gap-2"><button className="btn" onClick={()=>{setRecord(picked,{asked:true});toast.success('به‌عنوان پرسیده‌شده ثبت شد');setPicked('')}}>ثبت پرسیده‌شدن</button><button className="btn" onClick={()=>open('grade',{studentId:picked,type:'پرسش شفاهی',value:'',max:course.gradeScales?.['پرسش شفاهی']??20,note:'',competency:'1'})}>ثبت نمره پاسخ</button></div>}</div>}
 {modal==='import'&&<div className="stack"><div className="hint">فایل XLSX، XLS یا CSV تا ۵ مگابایت؛ حداکثر ۲۰۰۰ دانش‌آموز در هر بار. ستون‌های کد دانش‌آموزی، نام، نام خانوادگی، نام پدر، رشته و پایه با هر ترتیب و با ستون خالی شناسایی می‌شوند. این بخش به حساب سیدا متصل نمی‌شود.</div><Field label="کلاس مقصد"><Choice label="کلاس مقصد" value={form.classId} onChange={v=>patchForm('classId',v)} options={classOptions}/></Field><input aria-label="انتخاب فایل اکسل" type="file" accept=".xlsx,.xls,.csv" onChange={e=>{const f=e.target.files?.[0];if(f)void run(async()=>{const result=await readExcel(f);setSheets(result);setSheetIndex(0);setHeaderRow(0);const h=result[0]?.rows[0]||[];const found=detectSidaHeaders(h);setMapping({name:String(found.name<0?0:found.name),last:found.last<0?'none':String(found.last),code:String(found.code<0?0:found.code)});})}}/>{sheets.length>0&&<><div className="form-grid"><Field label="برگه اکسل"><Choice label="برگه" value={String(sheetIndex)} onChange={v=>{setSheetIndex(Number(v));setHeaderRow(0)}} options={sheets.map((s,i)=>({value:String(i),label:s.name}))}/></Field><Field label="شماره ردیف عنوان ستون‌ها"><input type="number" min="1" max="50" value={headerRow+1} onChange={e=>setHeaderRow(Math.max(0,Math.min(49,Number(e.target.value)-1)))}/></Field>{(['name','last','code'] as const).map(k=><Field key={k} label={k==='name'?'ستون نام یا نام کامل':k==='last'?'نام خانوادگی جداگانه (اختیاری)':'ستون کد دانش‌آموزی'}><Choice label="انتخاب ستون" value={mapping[k]} onChange={v=>setMapping(m=>({...m,[k]:v}))} options={[...(k==='last'?[{value:'none',label:'ستون جدا ندارد'}]:[]),...header.map((h,i)=>({value:String(i),label:`${i+1} · ${h||'بدون عنوان'}`}))]}/></Field>)}</div><p>{fa(importValid.length)} قابل ورود · {fa(duplicateCount)} کد تکراری · {fa(invalidCount)} ردیف ناقص</p><Table><TableHeader><TableRow><TableHead>ردیف فایل</TableHead><TableHead>نام</TableHead><TableHead>کد</TableHead></TableRow></TableHeader><TableBody>{importValid.slice(0,5).map((s,i)=><TableRow key={i}><TableCell>{fa(s.row)}</TableCell><TableCell>{s.name}</TableCell><TableCell>{s.code}</TableCell></TableRow>)}</TableBody></Table><button className="btn primary" disabled={!importValid.length||!form.classId||busy} onClick={()=>{if(importRows.length>2000){setModalError('فایل بیش از ۲۰۰۰ ردیف دارد؛ آن را تقسیم کنید');return}if(mapping.name===mapping.code){setModalError('ستون نام و کد نباید یکسان باشد');return}update(d=>d.students.push(...importValid.map(s=>({id:uid(),name:s.name,code:s.code,classId:form.classId}))));setModal('');toast.success(`${fa(importValid.length)} دانش‌آموز وارد شد`)}}>ورود {fa(importValid.length)} دانش‌آموز</button></>}<button className="btn" onClick={()=>void run(async()=>{await exportExcel('الگوی ورود دانش‌آموزان',[['نام و نام خانوادگی','کد دانش‌آموزی'],['دانش‌آموز نمونه','0012345678']])})}><Download size={16}/> دریافت الگوی اکسل</button></div>}
 {modal==='suggestions'&&<div className="stack"><div className="hint">فرمول مستمر: <code dir="ltr">{course?.formula.expression}</code><br/>فقط خانه‌های خالی پر می‌شوند. نمره کلی دستی و نمرات قبلی دست‌نخورده می‌مانند. پیشنهاد نهایی جای استاندارد ارزشیابی درس را نمی‌گیرد.</div><Table><TableHeader><TableRow>{['دانش‌آموز','شواهد','مستمر','شایستگی‌ها','نهایی پیشنهادی'].map(x=><TableHead key={x}>{x}</TableHead>)}</TableRow></TableHeader><TableBody>{form.proposals?.map(p=><TableRow key={p.id}><TableCell>{data.students.find(s=>s.id===p.id)?.name}</TableCell><TableCell>{fa(p.value.count)} نمره · میانگین {fa(p.value.average??0)}</TableCell><TableCell>{fa(p.value.continuous)}</TableCell><TableCell>{p.value.competencies.map(x=>x===null?'—':fa(x)).join(' / ')}</TableCell><TableCell>{p.value.competency===null?'شواهد ناکافی':fa(p.value.competency)}</TableCell></TableRow>)}</TableBody></Table><button className="btn primary" onClick={()=>{update(d=>form.proposals.forEach(p=>{const key=finalKey(course.id,module,p.id),f=d.finals[key]||blankFinal();d.finals[key]={...f,continuous:f.continuous??p.value.continuous,competencies:f.competencies.map((v,i)=>v??p.value.competencies[i]??null),competency:f.competency??(f.competencies.every(v=>v===null)?p.value.competency:null)}}));setModal('');toast.success('پیشنهادها در خانه‌های خالی اعمال شدند')}}>پیشنهادها را بررسی کردم؛ اعمال شود</button></div>}
 {modal==='studentReport'&&course&&<div className="stack"><h2>{data.students.find(s=>s.id===target)?.name}</h2>{a.audit&&target&&<GradeAudit offeringId={course.id} studentId={target} moduleIndex={module} name={data.students.find(s=>s.id===target)?.name}/>}<p>{course.name} · {classroom?.name}</p><Table><TableHeader><TableRow><TableHead>پودمان</TableHead><TableHead>میانگین عملکرد</TableHead><TableHead>حضور</TableHead><TableHead>نمره نهایی</TableHead></TableRow></TableHeader><TableBody>{course.modules.map((m,i)=>{const p=performance(data,course.id,i,target),f=getFinal(target,i),t=totalOf(f);return <TableRow key={i}><TableCell>{m.name}</TableCell><TableCell>{p.average===null?'—':fa(p.average)}</TableCell><TableCell>{p.records.some(r=>r.attendance!=='unset')?fa(p.values.attendance)+'٪':'—'}</TableCell><TableCell>{t===null?'—':fa(t)}</TableCell></TableRow>})}</TableBody></Table><button className="btn" onClick={()=>open('discipline',{studentId:target,date:today(),title:'',detail:''})}>ثبت گزارش انضباطی</button><h3>سوابق جلسات این پودمان</h3>{sessions.map(s=>{const r=s.records[target];return <div className="history-row" key={s.id}><b>{jalali(s.date)} · {s.title}</b><p>{attendance.find(a=>a.value===(r?.attendance||'unset'))?.label} · {r?.note||'بدون یادداشت'}</p><div className="marks">{r?.marks.map(m=><span className="mark-chip" key={m.id}>{m.type}: {markLabel(m)} {m.note&&'· '+m.note}</span>)}</div></div>})}<button className="btn" onClick={()=>window.print()}><Printer size={16}/> چاپ کارنامه</button></div>}
 {modal==='help'&&<div className="stack"><p>۱. در «کلاس‌ها و درس‌ها» کلاس، پایه، رشته و درس را تعریف کنید. هر درس پنج پودمان دارد.</p><p>۲. از «دانش‌آموزان» فهرست اکسل یا خروجی سیدا را وارد کنید؛ یا افراد را دستی اضافه کنید.</p><p>۳. در «دفتر کلاس» درس و پودمان را انتخاب و جلسه ایجاد کنید. حضور، نمره و یادداشت همان‌جا ثبت می‌شود.</p><p>۴. در پایان پودمان، مستمر و شایستگی را ثبت کنید یا پیشنهاد محاسباتی را بررسی کنید. تأیید مهارت با شماست.</p><p>۵. کارنامه را چاپ و نمرات را به اکسل صادر کنید. مرتب از تنظیمات پشتیبان بگیرید.</p><div className="hint">برای افزودن وب‌اپ به صفحه اصلی موبایل، از منوی مرورگر «افزودن به صفحه اصلی» را انتخاب کنید. ثبت اطلاعات به اینترنت و اتصال به هاست نیاز دارد.</div><a className="text-link" target="_blank" rel="noreferrer" href="https://www.roshdmag.ir/Roshdmag_content/media/article/144.149%20from%20MATN%20VIJENAMEH%20FANIHERFEIEE-19_0.pdf">مرجع آموزشی ارزشیابی شایستگی — رشد (۱۳۹۶)</a><p>این مرجع تاریخی است؛ تنظیمات نمره‌دهی را با شیوه‌نامه جاری مدرسه تطبیق دهید.</p></div>}
 </DialogContent></Dialog>
}
