import type {AppContext} from './context';
"use client";
import {useEffect,useRef,useState} from 'react';
import {BookOpen,Users,ClipboardCheck,ChartNoAxesCombined,Settings,GraduationCap,Plus,CloudCheck,ChevronLeft,LogOut,ShieldCheck,HelpCircle,FolderOpen} from 'lucide-react';
import {SidebarProvider,Sidebar,SidebarContent,SidebarHeader,SidebarFooter,SidebarTrigger} from '@/components/ui/sidebar';
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {Toaster} from '@/components/ui/sonner';
import {toast} from 'sonner';
import {Data,FinalGrade,sampleData,blankRecord,blankFinal,finalKey,totalOf,normalize,today} from '@/lib/model';
import {api,useAutosave} from '@/lib/api';
import {exportExcel} from '@/lib/excel';
import {Choice,Field} from './widgets';
import {Panels} from './panels';
import {Modals} from './modals';
import {Management,roleNames} from './management';
import {SchoolOffice} from './school-office';
const menus=[{id:'school',title:'غیبت و انضباط',icon:ClipboardCheck},{id:'management',title:'مدیریت مدرسه',icon:ShieldCheck},{id:'journal',title:'دفتر کلاس',icon:BookOpen},{id:'students',title:'دانش‌آموزان',icon:Users},{id:'courses',title:'کلاس‌ها و درس‌ها',icon:FolderOpen},{id:'finals',title:'نمرات پودمانی',icon:ClipboardCheck},{id:'reports',title:'کارنامه و عملکرد',icon:ChartNoAxesCombined},{id:'settings',title:'تنظیمات',icon:Settings}];
const demoAtStart=()=>new URLSearchParams(location.search).has('demo')||Boolean(import.meta.env.DEV&&!new URLSearchParams(location.search).has('live'));
export default function Home(){
 const [demo,setDemo]=useState(demoAtStart),[data,setData]=useState<Data|null>(()=>demoAtStart()?sampleData():null),[auth,setAuth]=useState<any>(null),[loading,setLoading]=useState(!demoAtStart()),[ownerId,setOwnerId]=useState<number|null>(null),[switching,setSwitching]=useState(false),[demoRole,setDemoRole]=useState('admin'),[revision,setRevision]=useState(0),[authError,setAuthError]=useState(''),[page,setPage]=useState(demoAtStart()?'management':'journal'),[courseId,setCourseId]=useState('l1'),[module,setModule]=useState(0),[sessionId,setSessionId]=useState('j1'),[tab,setTab]=useState('attendance'),[query,setQuery]=useState(''),[classFilter,setClassFilter]=useState('all'),[modal,setModal]=useState(''),[target,setTarget]=useState(''),[form,setForm]=useState<any>({}),[modalError,setModalError]=useState(''),[busy,setBusy]=useState(false),[confirm,setConfirm]=useState<{title:string;body:string;action:()=>void}|null>(null);
 const currentOwner=useRef(ownerId);currentOwner.current=ownerId;
 const current=useRef(data);current.current=data;
 const saver=useAutosave(data,!demo&&Boolean(auth),revision,ownerId);
 const role=demo?demoRole:auth?.role,staff=['admin','deputy'].includes(role),foreign=ownerId!==null&&ownerId!==(auth?.id??1);
 const visibleMenus=menus.filter(m=>(!['management','school'].includes(m.id)||staff)&&(m.id!=='settings'||!foreign));
 async function openWorkspace(id:number,nextPage='students'){
  if(switching)return;
  if(!demo&&!saver.isClean()){toast.error('پیش از تغییر دفتر، منتظر ذخیره کامل تغییرات بمانید');return}
  setSwitching(true);try{
   const r=demo?{data:sampleData(),revision:0,workspaceId:id}:await api('workspace_open',{userId:id});
   if(demo)r.data.profile.name=id===1?'سعید آذرمهر':id===2?'معاون نمونه':'معلم نمونه';
   setData(r.data);setRevision(r.revision);setOwnerId(r.workspaceId);setCourseId('');setModule(0);setSessionId('');setClassFilter('all');setQuery('');setModal('');setPage(nextPage);
  }catch(e){toast.error((e as Error).message)}finally{setSwitching(false)}
 }

 useEffect(()=>{if(demo)return;api('session').then(r=>{setAuth(r.user);if(r.user){setRevision(r.revision);setOwnerId(r.workspaceId);setData(r.data);setPage(r.user.role==='teacher'?'journal':'management')}}).catch(e=>setAuthError(e.message)).finally(()=>setLoading(false))},[demo]);
 useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const controller=new AbortController();Promise.resolve(context.registerTool({name:'read_class_overview',title:'خلاصه کلاس',description:'Read counts in the signed-in teacher workspace without modifying grades.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:(input:unknown)=>{if(!input||typeof input!=='object'||Object.keys(input).length)throw Error('No parameters accepted');const d=current.current;if(!d)throw Error('Sign in first');return {classes:d.classes.length,courses:d.courses.length,students:d.students.length,sessions:d.sessions.length}}},{signal:controller.signal})).catch(()=>{});return()=>controller.abort()},[]);
 const update=(fn:(d:Data)=>void)=>setData(prev=>{if(!prev||switching)return prev;const next=structuredClone(prev);fn(next);return next});
 const course=data?.courses.find(c=>c.id===courseId)||data?.courses[0];const classroom=data?.classes.find(c=>c.id===course?.classId);const sessions=data?.sessions.filter(s=>s.courseId===course?.id&&s.module===module)||[];const session=sessions.find(s=>s.id===sessionId)||sessions.at(-1);const allStudents=data?.students.filter(s=>s.classId===course?.classId)||[];const students=allStudents.filter(s=>normalize(s.name+' '+s.code).includes(normalize(query)));const moduleInfo=course?.modules[module];
 const open=(name:string,value:any={},id='')=>{if(role!=='teacher'&&['grade','formula','scales','session','picker','suggestions'].includes(name))return;setModalError('');setForm(value);setTarget(id);setModal(name)};
 const patchForm=(key:string,value:unknown)=>setForm((prev:any)=>({...prev,[key]:value}));
 const record=(id:string)=>session?.records[id]||blankRecord();
 const setRecord=(id:string,patch:any)=>{if(!session){toast.error('ابتدا یک جلسه ایجاد کنید');return}update(d=>{const s=d.sessions.find(x=>x.id===session.id)!;s.records[id]={...(s.records[id]||blankRecord()),...patch}})};
 const getFinal=(id:string,m=module):FinalGrade=>data?.finals[finalKey(course!.id,m,id)]||blankFinal();
 const setFinal=(id:string,patch:Partial<FinalGrade>)=>update(d=>{const key=finalKey(course!.id,module,id);d.finals[key]={...(d.finals[key]||blankFinal()),...patch}});
 const run=async(fn:()=>Promise<void>)=>{setBusy(true);setModalError('');try{await fn()}catch(e){setModalError((e as Error).message);toast.error((e as Error).message)}finally{setBusy(false)}};
 const downloadBackup=()=>{if(!data)return;const a=document.createElement('a'),url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.href=url;a.download='poodman-backup-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
 async function exportGrades(){if(!course||!data)return;await exportExcel(course.name,[['کد دانش‌آموزی','نام و نام خانوادگی',...course.modules.map((m,i)=>`پودمان ${i+1}: ${m.name}`),'میانگین ثبت‌شده'],...allStudents.map(s=>{const a=course.modules.map((_,m)=>totalOf(getFinal(s.id,m)));const existing=a.filter(v=>v!==null) as number[];return [s.code,s.name,...a,existing.length?Number((existing.reduce((a,b)=>a+b,0)/existing.length).toFixed(2)):null]})]);toast.success('فایل اکسل آماده شد')}
 const classOptions=data?.classes.map(c=>({value:c.id,label:c.name}))||[];const courseOptions=data?.courses.map(c=>({value:c.id,label:c.name+' · '+(data.classes.find(x=>x.id===c.classId)?.name||'')}))||[];
 const ctx={ownerId,foreign,staff,role,readOnlyGrades:role!=='teacher',demo,data:data!,auth,page,setPage,courseId,setCourseId,module,setModule,sessionId,setSessionId,tab,setTab,query,setQuery,classFilter,setClassFilter,modal,setModal,target,form,setForm,modalError,setModalError,busy,setConfirm,update,open,patchForm,record,setRecord,getFinal,setFinal,run,downloadBackup,exportGrades,classOptions,courseOptions,course,classroom,sessions,session,allStudents,students,moduleInfo,setData};
 if(loading)return <div className="auth-wrap"><div className="auth-card"><GraduationCap size={40}/><h1>دفتر کلاسی آنلاین آذرمهر</h1><p>در حال اتصال به دفتر شما…</p></div></div>;
 if(!demo&&!auth)return <><Toaster position="top-center" dir="rtl"/><div className="auth-wrap"><form className="auth-card stack" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void run(async()=>{setAuthError('');const r=await api('login',{email:f.get('email'),password:f.get('password')});setRevision(r.revision);setOwnerId(r.workspaceId);setData(r.data);setAuth(r.user);setPage(r.user.role==='teacher'?'journal':'management')})}}><div className="brand"><span className="brand-mark"><GraduationCap/></span><div><b>دفتر کلاسی آنلاین آذرمهر</b><small>دفتر هوشمند معلم</small></div></div><h1>خوش آمدید</h1><p>برای ورود به دفتر شخصی خود، مشخصات حساب را وارد کنید.</p>{(authError||modalError)&&<div className="error">{authError||modalError}</div>}<Field label="ایمیل"><input name="email" type="email" autoComplete="username" dir="ltr" required/></Field><Field label="رمز عبور"><input name="password" type="password" autoComplete="current-password" required/></Field><button disabled={busy} className="btn primary">ورود به دفتر</button><button type="button" className="btn" onClick={()=>{setData(sampleData());setDemo(true)}}>مشاهده نسخه نمایشی</button><a className="text-link" href="./install.php">نصب اولیه روی هاست</a><small>طراحی و توسعه: سعید آذرمهر</small></form></div></>;
 if(!data)return null;
 return <SidebarProvider dir="rtl"><Toaster position="top-center" dir="rtl"/><Sidebar side="right"><SidebarHeader><div className="brand"><span className="brand-mark"><GraduationCap/></span><div><b>دفتر کلاسی آنلاین آذرمهر</b><small>دفتر هوشمند معلم</small></div></div></SidebarHeader><SidebarContent><div className="nav-label">فضای آموزشی من</div>{visibleMenus.map(m=><button key={m.id} onClick={()=>{setPage(m.id);setQuery('')}} className={'nav-item '+(page===m.id?'active':'')}><m.icon size={20}/>{m.title}</button>)}<div className="sidebar-tip"><ShieldCheck size={22}/><b>دفتر شما، همیشه مرتب</b><p>{demo?'این محیط نمایشی است. اطلاعات واقعی دانش‌آموزان را اینجا وارد نکنید.':'تغییرات به‌صورت خودکار در حساب شما ذخیره می‌شوند.'}</p></div><button className="nav-item" onClick={()=>open('help')}><HelpCircle size={19}/> راهنمای سریع</button></SidebarContent><SidebarFooter><button className="teacher" onClick={()=>{if(!foreign)setPage('settings')}}><span className="avatar">{data.profile.name.slice(0,1)||'م'}</span><div><b>{data.profile.name||'معلم'}</b><small>{(demo?'نمایشی · ':'')+(foreign?'دفتر همکار':roleNames[role]||'معلم')}</small></div></button><small className="credit">طراحی و توسعه: سعید آذرمهر</small></SidebarFooter></Sidebar><div className="workspace"><header className="topbar"><div className="flex items-center gap-3"><SidebarTrigger/><span>سال تحصیلی {data.profile.year}</span></div><div className="flex items-center gap-4"><span aria-live="polite" className={'saved '+(saver.error?'text-red-600':'')}><CloudCheck size={17}/>{demo?'حالت نمایشی · ذخیره موقت':saver.status==='saved'?'همه تغییرات ذخیره شد':saver.status==='error'?'ذخیره انجام نشد':'در حال ذخیره…'}</span><button aria-label="خروج" className="icon-btn" onClick={()=>{if(!demo&&!saver.isClean()){toast.error('ابتدا منتظر ذخیره شوید یا نسخه پشتیبان بگیرید');return}setConfirm({title:'خروج از دفتر',body:demo?'تغییرات نمایشی با خروج پاک می‌شوند.':'از حساب خود خارج می‌شوید.',action:()=>{if(demo){setDemo(false);setData(null);setAuth(null);return}void api('logout',{}).then(()=>{setAuth(null);setData(null)})}})}}><LogOut size={18}/></button></div></header><main className="content">
 {demo&&<div className="demo-role"><span>پیش‌نمایش نقش‌ها</span><Choice label="نقش نمایشی" value={demoRole} onChange={v=>{setDemoRole(v);setOwnerId(null);setData(sampleData());setPage(v==='teacher'?'journal':'management')}} options={Object.entries(roleNames).map(([value,label])=>({value,label}))}/></div>}
 {foreign&&<div className="managed-banner"><ShieldCheck size={22}/><div><b>دفتر {data.profile.name}</b><p>مدیریت دانش‌آموز و کلاس فعال است؛ جلسات، نمرات و فرمول فقط قابل مشاهده‌اند.</p></div><button disabled={switching} className="btn" onClick={()=>void openWorkspace(auth?.id??1,'management')}>بازگشت به دفتر من</button></div>}
 {switching&&<p role="status">در حال بازکردن دفتر…</p>}

 {saver.error&&<div className="error mb-5">{saver.error} <button className="btn" onClick={downloadBackup}>دریافت تغییرات ذخیره‌نشده</button> {!saver.blocked&&<button className="btn" onClick={saver.retry}>تلاش مجدد</button>}{saver.blocked&&<button className="btn" onClick={()=>setConfirm({title:'بارگذاری نسخه سرور',body:'تغییرات ذخیره‌نشده کنار گذاشته می‌شوند. ابتدا فایل پشتیبان را دریافت کنید.',action:()=>location.reload()})}>بارگذاری مجدد</button>}</div>}
 <div className="page-heading"><div><div className="eyebrow">فضای آموزشی من <ChevronLeft size={14}/> {menus.find(m=>m.id===page)?.title}</div><h1>{page==='journal'?'امروز، یک قدم جلوتر':menus.find(m=>m.id===page)?.title}</h1><p>{page==='journal'?'همه‌چیز برای یک جلسه‌ی خوب، همین‌جاست.':page==='students'?'فهرست دانش‌آموزان و کلاسبندی، یک‌جا و مرتب.':page==='finals'?'جمع‌بندی تلاش هر دانش‌آموز در پایان پودمان.':page==='reports'?'پیشرفت را ببینید، مسیر یادگیری را بهتر کنید.':page==='courses'?'کلاس و درس را تعریف کنید؛ دفترتان آماده است.':page==='management'?'همکاران، کلاس‌ها و دسترسی‌های مدرسه.':page==='school'?'غیبت‌های روز، سابقه حضور و پیگیری گزارش‌های انضباطی.':'دفتر را به شیوه خودتان تنظیم کنید.'}</p></div>{page==='journal'&&role==='teacher'&&<button disabled={!course} className="btn primary" onClick={()=>open('session',{date:today(),title:''})}><Plus size={18}/> جلسه جدید</button>}{page==='students'&&<button className="btn primary" disabled={!data.classes.length} onClick={()=>open('student',{name:'',code:'',classId:classFilter==='all'?data.classes[0]?.id:classFilter})}><Plus size={18}/> دانش‌آموز جدید</button>}{page==='courses'&&<button className="btn primary" onClick={()=>open('class',{name:'',grade:'دهم',major:'',year:data.profile.year})}><Plus size={18}/> کلاس جدید</button>}</div>
 {['journal','finals','reports'].includes(page)&&<section className="class-banner"><div className="course-icon"><BookOpen size={28}/></div><div className="course-selector"><Choice value={course?.id||''} onChange={v=>{setCourseId(v);setModule(0);setSessionId('')}} options={courseOptions} label="انتخاب درس"/><p>{classroom?.grade} {classroom?.major&&'• '+classroom.major} {classroom?.year&&'• '+classroom.year}</p></div><Choice value={String(module)} onChange={v=>{setModule(Number(v));setSessionId('')}} options={(course?.modules||[]).map((m,i)=>({value:String(i),label:`پودمان ${i+1} · ${m.name}`}))} label="انتخاب پودمان"/></section>}
 {page==='school'&&staff?<SchoolOffice key={demo?demoRole:auth?.id} demo={demo} canManage={()=>demo||saver.isClean()} onChanged={async(id:number)=>{if(currentOwner.current===id){const r=await api('workspace_open',{userId:id});if(currentOwner.current===id){setData(r.data);setRevision(r.revision)}}}}/>:page==='management'&&staff?<Management demo={demo} auth={demo?{id:1,role:demoRole}:auth} onOpen={openWorkspace}/>:<Panels ctx={ctx as AppContext}/>}</main></div><Modals ctx={ctx as AppContext}/><AlertDialog open={Boolean(confirm)} onOpenChange={v=>{if(!v)setConfirm(null)}}><AlertDialogContent dir="rtl"><AlertDialogHeader><AlertDialogTitle>{confirm?.title}</AlertDialogTitle><AlertDialogDescription>{confirm?.body}</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>انصراف</AlertDialogCancel><AlertDialogAction onClick={()=>{confirm?.action();setConfirm(null)}}>تأیید</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></SidebarProvider>
}
