import {useEffect,useRef,useState} from 'react';
import {CalendarDays,Printer,Download,Plus,RefreshCw} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Choice,Field,Empty,attendance} from './widgets';
import {api} from '@/lib/api';
import {exportExcel} from '@/lib/excel';
import {fa,normalize,sampleData,today} from '@/lib/model';
import {toast} from 'sonner';
const caseStates=[{value:'open',label:'باز'},{value:'in_progress',label:'در حال پیگیری'},{value:'resolved',label:'رسیدگی‌شده'}];
const dateLabel=(date:string)=>new Date(date+'T12:00:00').toLocaleDateString('fa-IR');
const past=(days:number)=>{const d=new Date(today()+'T12:00:00Z');d.setUTCDate(d.getUTCDate()-days);return d.toISOString().slice(0,10)};
type Owner={id:number;name:string;email:string;classes:{id:string;name:string}[];students:{id:string;name:string;code:string;classId:string}[]};
export function SchoolOffice({demo,canManage,onChanged}:{demo:boolean;canManage:()=>boolean;onChanged:(id:number)=>Promise<void>}){
 const [tab,setTab]=useState('day'),[from,setFrom]=useState(today),[to,setTo]=useState(today),[owner,setOwner]=useState('all'),[classId,setClassId]=useState('all'),[status,setStatus]=useState('issues'),[caseStatus,setCaseStatus]=useState('all'),[query,setQuery]=useState(''),[owners,setOwners]=useState<Owner[]>([]),[rows,setRows]=useState<any[]>([]),[cases,setCases]=useState<any[]>([]),[error,setError]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[truncated,setTruncated]=useState(false),[form,setForm]=useState<any>(null),[kind,setKind]=useState('attendance');
 const request=useRef(0),demoStore=useRef<{rows:any[];cases:any[];owners:Owner[]}|null>(null);
 if(!demoStore.current){const d=sampleData();demoStore.current={owners:[{id:3,name:'معلم نمونه',email:'teacher@example.test',classes:d.classes,students:d.students}],rows:d.students.map(s=>({ownerId:3,ownerName:'معلم نمونه',revision:0,sessionId:'j1',sessionTitle:d.sessions[0].title,date:today(),course:d.courses[0].name,classId:s.classId,className:d.classes[0].name,studentId:s.id,studentName:s.name,studentCode:s.code,attendance:d.sessions[0].records[s.id].attendance,teacherNote:d.sessions[0].records[s.id].note,followup:''})),cases:[{id:1,owner_id:3,student_id:'s3',student_name:d.students[3].name,student_code:d.students[3].code,class_id:'c1',class_name:d.classes[0].name,event_date:today(),title:'نیاز به پیگیری تأخیرهای مکرر',detail:'گزارش نمونه برای نمایش روند پیگیری.',followup:'',status:'open',revision:0,creator:'معلم نمونه',updater:'معلم نمونه',ownerEmail:'teacher@example.test'}]};}
 async function load(){const id=++request.current;setLoading(true);setError('');setRows([]);setCases([]);try{
  if(from>to)throw Error('تاریخ پایان باید پس از تاریخ شروع باشد');
  if(demo){const d=demoStore.current!;setOwners(d.owners);setRows(d.rows.filter(r=>r.date>=from&&r.date<=to&&(owner==='all'||r.ownerId===Number(owner))&&(status==='all'||status==='issues'&&['absent','excused','late'].includes(r.attendance)||r.attendance===status)));setCases(d.cases.filter(r=>r.event_date>=from&&r.event_date<=to&&(owner==='all'||Number(r.owner_id)===Number(owner))&&(caseStatus==='all'||r.status===caseStatus)));setTruncated(false);return}
  const [roster,result]=await Promise.all([api('school_roster',{}),api(tab==='discipline'?'incident_list':'attendance_list',{from,to,ownerId:owner==='all'?0:Number(owner),status:tab==='discipline'?caseStatus:status})]);if(id!==request.current)return;
  setOwners(roster.owners);setTruncated(result.truncated);if(tab==='discipline')setCases(result.rows);else setRows(result.rows);
 }catch(e){if(id===request.current)setError((e as Error).message)}finally{if(id===request.current)setLoading(false)}}
 useEffect(()=>{const timer=setTimeout(()=>void load(),250);return()=>{clearTimeout(timer);request.current++}},[tab,from,to,owner,status,caseStatus]);
 const classes=owners.filter(o=>owner==='all'||String(o.id)===owner).flatMap(o=>o.classes.map(c=>({value:o.id+':'+c.id,label:c.name+' · '+o.name})));
 const visibleRows=rows.filter(r=>(classId==='all'||classId===r.ownerId+':'+r.classId)&&normalize(r.studentName+' '+r.studentCode).includes(normalize(query)));
 const visibleCases=cases.filter(r=>(classId==='all'||classId===r.owner_id+':'+r.class_id)&&normalize(r.student_name+' '+r.student_code+' '+r.title).includes(normalize(query)));
 function chooseTab(v:string){setTab(v);if(v==='day'){setFrom(today());setTo(today())}else if(tab==='day'){setFrom(past(30));setTo(today())}}
 function openAttendance(r:any){setError('');setKind('attendance');setForm({...r})}
 function openCase(r?:any){setError('');setKind('case');const o=owners.find(x=>String(x.id)===owner)||owners[0];setForm(r?{...r,date:r.event_date,ownerId:Number(r.owner_id),studentId:r.student_id}:{ownerId:o?.id||0,studentId:'',date:today(),title:'',detail:'',followup:'',status:'open'})}
 async function save(){if(!canManage()){setError('ابتدا منتظر ذخیره تغییرات دفتر بمانید');return}setBusy(true);setError('');try{
  if(demo){const d=demoStore.current!;if(kind==='attendance')d.rows=d.rows.map(r=>r.ownerId===form.ownerId&&r.sessionId===form.sessionId&&r.studentId===form.studentId?{...r,attendance:form.attendance,followup:form.followup}:r);else if(form.id)d.cases=d.cases.map(r=>r.id===form.id?{...r,...form,event_date:form.date}:r);else{const o=d.owners.find(x=>x.id===form.ownerId),s=o?.students.find(x=>x.id===form.studentId);if(!s)throw Error('دانش‌آموز را انتخاب کنید');d.cases.push({...form,id:Date.now(),owner_id:form.ownerId,student_id:s.id,student_name:s.name,student_code:s.code,class_id:s.classId,class_name:o!.classes.find(c=>c.id===s.classId)?.name,event_date:form.date,creator:'مدیر نمایشی',updater:'مدیر نمایشی',ownerEmail:o!.email,revision:0})}}
  else if(kind==='attendance'){await api('attendance_update',form);await onChanged(form.ownerId)}else await api(form.id?'incident_update':'incident_create',{...form,id:form.id?Number(form.id):undefined,revision:form.id?Number(form.revision):undefined});
  setForm(null);await load();toast.success(demo?'تغییر در پیش‌نمایش اعمال شد':'تغییرات ثبت شد');
 }catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function download(){try{if(tab==='discipline')await exportExcel('گزارش انضباطی',[['تاریخ','نام','کد','کلاس','دفتر','موضوع','شرح','وضعیت','پیگیری','ثبت‌کننده'],...visibleCases.map(r=>[r.event_date,r.student_name,r.student_code,r.class_name,r.ownerEmail,r.title,r.detail,caseStates.find(s=>s.value===r.status)?.label||'',r.followup,r.creator])]);else await exportExcel('گزارش غیبت و حضور',[['تاریخ','نام','کد','کلاس','درس','معلم','جلسه','حضور','یادداشت معلم','پیگیری'],...visibleRows.map(r=>[r.date,r.studentName,r.studentCode,r.className,r.course,r.ownerName,r.sessionTitle,attendance.find(s=>s.value===r.attendance)?.label||'',r.teacherNote,r.followup])])}catch(e){setError((e as Error).message)}}
 const patch=(k:string,v:any)=>setForm((f:any)=>({...f,[k]:v}));
 return <div className="school-office stack"><Tabs value={tab} onValueChange={chooseTab} dir="rtl"><TabsList className="school-tabs"><TabsTrigger value="day">غیبت‌های روز</TabsTrigger><TabsTrigger value="history">سابقه حضور</TabsTrigger><TabsTrigger value="discipline">گزارش انضباطی</TabsTrigger></TabsList></Tabs>
 <section className="panel p-5 school-filters"><Field label="از تاریخ"><input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></Field><Field label="تا تاریخ"><input type="date" value={to} onChange={e=>setTo(e.target.value)}/></Field><Field label="دفتر معلم"><Choice label="دفتر معلم" value={owner} onChange={v=>{setOwner(v);setClassId('all')}} options={[{value:'all',label:'همه دفترها'},...owners.map(o=>({value:String(o.id),label:o.name+' · '+o.email}))]}/></Field><Field label="کلاس"><Choice label="کلاس گزارش" value={classId} onChange={setClassId} options={[{value:'all',label:'همه کلاس‌ها'},...classes]}/></Field><Field label="وضعیت"><Choice label="وضعیت گزارش" value={tab==='discipline'?caseStatus:status} onChange={tab==='discipline'?setCaseStatus:setStatus} options={tab==='discipline'?[{value:'all',label:'همه وضعیت‌ها'},...caseStates]:[{value:'issues',label:'غیبت و تأخیر'},{value:'all',label:'همه ثبت‌ها'},...attendance]}/></Field><Field label="جست‌وجو"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="نام یا کد دانش‌آموز…"/></Field></section>
 <div className="office-actions"><button className="btn" disabled={loading} onClick={()=>void load()}><RefreshCw size={16}/> تازه‌سازی</button><button className="btn" disabled={loading||Boolean(error)} onClick={()=>window.print()}><Printer size={16}/> چاپ گزارش</button><button className="btn" disabled={loading||Boolean(error)} onClick={()=>void download()}><Download size={16}/> اکسل گزارش</button>{tab==='discipline'&&<button className="btn primary" disabled={!owners.length} onClick={()=>openCase()}><Plus size={16}/> گزارش جدید</button>}</div>
 <div className="report-period"><h2>{tab==='discipline'?'گزارش‌های انضباطی':tab==='day'?'غیبت و تأخیر روز':'سابقه حضور و غیبت'}</h2><p>{from&&dateLabel(from)} تا {to&&dateLabel(to)} · {fa(tab==='discipline'?visibleCases.length:visibleRows.length)} ثبت{query&&' · جست‌وجو: '+query}</p><p>{tab==='discipline'?'گزارش‌های رفتاری مستقل از نمرات هستند.':'هر ردیف حضور مربوط به یک جلسه و یک دفتر است؛ تعداد ثبت‌ها معادل تعداد دانش‌آموز یکتا نیست.'}</p><p>{owner==='all'?'همه دفترها':owners.find(o=>String(o.id)===owner)?.name} · {classId==='all'?'همه کلاس‌ها':classes.find(c=>c.value===classId)?.label}</p></div>
 {error&&!form&&<div className="error" role="alert">{error}</div>}{truncated&&<div className="error">بیش از ۵۰۰۰ رکورد پیدا شد. این گزارش و خروجی آن کامل نیست؛ بازه تاریخ یا دفتر را محدود کنید.</div>}
 {loading?<p role="status">در حال دریافت گزارش…</p>:tab==='discipline'?<div className="office-cards">{!visibleCases.length&&<Empty text="گزارش انضباطی در این بازه پیدا نشد"/>}{visibleCases.map(r=><article className="panel p-5 office-card" key={r.id}><div className="office-card-title"><h3>{r.student_name}</h3><span className={'pill '+(r.status==='resolved'?'present':'late')}>{caseStates.find(s=>s.value===r.status)?.label}</span></div><p>{r.student_code} · {r.class_name} · {dateLabel(r.event_date)}</p><h3>{r.title}</h3><p className="preserve-lines">{r.detail}</p><p className="preserve-lines"><b>پیگیری: </b>{r.followup||'هنوز ثبت نشده'}</p><small>دفتر: {owners.find(o=>o.id===Number(r.owner_id))?.name||r.ownerEmail} · ثبت‌کننده: {r.creator} · آخرین ویرایش: {r.updater}</small><button className="btn" onClick={()=>openCase(r)}>بررسی و پیگیری</button></article>)}</div>:<div className="office-cards">{!visibleRows.length&&<Empty text="رکوردی در این بازه و فیلتر پیدا نشد"/>}{visibleRows.map(r=><article className="panel p-5 office-card" key={r.ownerId+':'+r.sessionId+':'+r.studentId}><div className="office-card-title"><h3>{r.studentName}</h3><span className={'pill '+r.attendance}>{attendance.find(s=>s.value===r.attendance)?.label}</span></div><p>{r.studentCode} · {r.className}</p><p><CalendarDays size={15}/>{dateLabel(r.date)} · {r.course}</p><p>{r.ownerName} · {r.sessionTitle}</p>{r.teacherNote&&<p className="preserve-lines">یادداشت معلم: {r.teacherNote}</p>}<p className="preserve-lines">پیگیری: {r.followup||'هنوز ثبت نشده'}</p><div className="flex gap-2 flex-wrap"><button className="btn" onClick={()=>openAttendance(r)}>اصلاح حضور / پیگیری</button><button className="btn" onClick={()=>{setQuery(r.studentCode);setTab('history');setFrom(past(365));setTo(today());setStatus('all')}}>سابقه این دانش‌آموز</button></div></article>)}</div>}
 <Dialog open={Boolean(form)} onOpenChange={v=>{if(!v&&!busy){setForm(null);setError('')}}}><DialogContent className="app-dialog" dir="rtl"><DialogTitle>{kind==='attendance'?'اصلاح حضور و ثبت پیگیری':form?.id?'رسیدگی به گزارش انضباطی':'گزارش انضباطی جدید'}</DialogTitle><DialogDescription>این عملیات نمره‌های ثبت‌شده را تغییر نمی‌دهد. تغییرات مدیریتی ثبت می‌شوند.</DialogDescription>{form&&<form className="stack" onSubmit={e=>{e.preventDefault();void save()}}>{error&&<div className="error" role="alert">{error}</div>}{kind==='attendance'?<><h3>{form.studentName}</h3><p>{form.className} · {dateLabel(form.date)} · {form.course}</p><Field label="وضعیت حضور"><Choice label="وضعیت حضور" value={form.attendance} onChange={v=>patch('attendance',v)} options={attendance}/></Field></>:<>{form.id?<h3>{form.student_name} · {form.class_name}</h3>:<><Field label="دفتر مقصد"><Choice label="دفتر مقصد" value={String(form.ownerId||'')} onChange={v=>{patch('ownerId',Number(v));patch('studentId','')}} options={owners.map(o=>({value:String(o.id),label:o.name+' · '+o.email}))}/></Field><Field label="دانش‌آموز"><Choice label="دانش‌آموز گزارش" value={form.studentId} onChange={v=>patch('studentId',v)} options={(owners.find(o=>o.id===form.ownerId)?.students||[]).map(s=>({value:s.id,label:s.name+' · '+s.code}))}/></Field></>}<Field label="تاریخ رویداد"><input type="date" required value={form.date} onChange={e=>patch('date',e.target.value)}/></Field><Field label="موضوع"><input required maxLength={150} value={form.title} onChange={e=>patch('title',e.target.value)}/></Field><Field label="شرح رویداد"><textarea required maxLength={2000} value={form.detail} onChange={e=>patch('detail',e.target.value)}/></Field><Field label="وضعیت رسیدگی"><Choice label="وضعیت رسیدگی" value={form.status} onChange={v=>patch('status',v)} options={caseStates}/></Field></>}<Field label="شرح پیگیری / دلیل اصلاح"><textarea maxLength={2000} value={form.followup} onChange={e=>patch('followup',e.target.value)} placeholder="مثلاً: تماس با خانواده، دریافت گواهی یا نتیجه رسیدگی"/></Field><button className="btn primary" disabled={busy||kind==='case'&&!form.studentId}>{busy?'در حال ثبت…':'ثبت تغییرات'}</button></form>}</DialogContent></Dialog>
 </div>
}
