import {useEffect,useRef,useState} from 'react';
import {Data} from './model';
let csrf='';
export async function api(action:string,body?:unknown):Promise<any>{const r=await fetch(`./api.php?action=${encodeURIComponent(action)}`,{method:body===undefined?'GET':'POST',credentials:'same-origin',headers:body===undefined?{}:{'Content-Type':'application/json','X-CSRF-Token':csrf},body:body===undefined?undefined:JSON.stringify(body)});let data:any;try{data=await r.json()}catch{throw Error('ارتباط با سرور برقرار نشد. نصب PHP و نشانی سایت را بررسی کنید.')}if(!r.ok)throw Object.assign(Error(data.error||'خطای سرور'),{status:r.status});if(data.csrf)csrf=data.csrf;return data}
export function useAutosave(data:Data|null,enabled:boolean,initialRevision:number,ownerId:number|null){const [status,setStatus]=useState('saved'),[error,setError]=useState('');const refs=useRef({data:null as Data|null,saved:'',revision:initialRevision,busy:false,blocked:false,timer:0});
 useEffect(()=>{const r=refs.current;r.revision=initialRevision;r.saved=JSON.stringify(data);r.blocked=false;setError('');setStatus('saved')},[enabled,initialRevision,ownerId]);
 async function flush(){const r=refs.current;if(!enabled||r.busy||r.blocked||!r.data)return;const snapshot=JSON.stringify(r.data);if(snapshot===r.saved)return;r.busy=true;setStatus('saving');try{const result=await api('save',{data:r.data,revision:r.revision,userId:ownerId});r.revision=result.revision;r.saved=snapshot;setError('');setStatus('saved')}catch(e){const x=e as Error&{status?:number};r.blocked=x.status===409||x.status===401||x.status===403;setError(x.message);setStatus('error')}finally{r.busy=false;if(!r.blocked&&r.saved!==JSON.stringify(r.data)){r.timer=window.setTimeout(flush,3000)}}}
 useEffect(()=>{refs.current.data=data;if(!enabled)return;if(JSON.stringify(data)!==refs.current.saved){setStatus('pending');window.clearTimeout(refs.current.timer);refs.current.timer=window.setTimeout(flush,650)}return ()=>window.clearTimeout(refs.current.timer)},[data,enabled,ownerId]);
 useEffect(()=>{const before=(e:BeforeUnloadEvent)=>{if(enabled&&JSON.stringify(refs.current.data)!==refs.current.saved){e.preventDefault();e.returnValue=''}};window.addEventListener('beforeunload',before);return ()=>window.removeEventListener('beforeunload',before)},[enabled]);
 return {isClean:()=>!refs.current.busy&&JSON.stringify(refs.current.data)===refs.current.saved,status,error,retry:()=>{if(!refs.current.blocked)void flush()},blocked:refs.current.blocked};
}
