import type {School} from './central-demo';import type {Dispatch,Life} from './school-life';
import {blankRecord,type Data,type FinalGrade,type RecordEntry,type Session} from './model';
import {cacheDeskData,enqueueMutation,getMutationsByStatus,getPendingMutations,listCachedDesks,offlineActor} from './offline-db';
let csrf='';export type SchoolState={d:School;life:Life};
async function ensureCsrf(){if(csrf)return;const r=await fetch('./school-api.php?action=session',{credentials:'same-origin'});const value=await r.json().catch(()=>({}));if(value.csrf)csrf=value.csrf}
export async function schoolAPI(action:string,body?:unknown){if(body!==undefined)await ensureCsrf();const r=await fetch('./school-api.php?action='+encodeURIComponent(action),{method:body===undefined?'GET':'POST',credentials:'same-origin',headers:body===undefined?{}:{'Content-Type':'application/json','X-CSRF-Token':csrf},body:body===undefined?undefined:JSON.stringify(body)});let value:any;try{value=await r.json()}catch{throw Error('ارتباط با سرور برقرار نشد؛ نصب و نسخه PHP را بررسی کنید.')}if(value.csrf)csrf=value.csrf;if(!r.ok)throw Object.assign(Error(value.error||'خطای سرور'),{status:r.status});return value}
export async function uploadAnswer(file:File,taskId:string){await ensureCsrf();const form=new FormData();form.append('file',file);form.append('taskId',taskId);const r=await fetch('./school-api.php?action=upload',{method:'POST',credentials:'same-origin',headers:{'X-CSRF-Token':csrf},body:form});const value=await r.json();if(value.csrf)csrf=value.csrf;if(!r.ok)throw Error(value.error||'بارگذاری انجام نشد');return value.file}
export type LiveSchool={state:SchoolState;actor:string;serial:number;status:string;onChange:(state:SchoolState)=>void;setDeskBusy?:(busy:boolean)=>void};
export function downloadJSON(value:unknown,name:string){const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
export type DeskSlice={offeringId:string;class:{id:string;name:string;yearId:string};students:{id:string;name:string;code:string}[];sessions:Session[];finals:Record<string,FinalGrade>};
export type DeskPlan={structural:boolean;urgent:boolean;attendance:{session_id:string;records:{student_id:string;attendance:string;asked:boolean;note:string}[]}[];marks:{session_id:string;student_id:string;marks:{id:string;type:string;value:number;max:number;note:string;competency:number}[]}[];finals:{offering_id:string;module_index:number;student_id:string;continuous:number|null;competencies:(number|null)[];final_competency:number|null;total:number|null;note:string}[]};
async function readBody(r:Response){let value:any;try{value=await r.json()}catch{if(!r.ok)throw Object.assign(Error('ارتباط با سرور برقرار نشد؛ نصب و نسخه PHP را بررسی کنید.'),{status:r.status});throw Error('ارتباط با سرور برقرار نشد؛ نصب و نسخه PHP را بررسی کنید.')}if(value.csrf)csrf=value.csrf;if(!r.ok)throw Object.assign(Error(value.error||'خطای سرور'),{status:r.status});return value}
export function rememberCsrf(token:string){if(token)csrf=token}
export function isTransportError(error:unknown){if(typeof navigator!=='undefined'&&!navigator.onLine)return true;if(error instanceof DOMException&&(error.name==='AbortError'||error.name==='TimeoutError'))return true;if(error instanceof TypeError)return true;const status=typeof error==='object'&&error&&'status' in error?Number((error as {status:unknown}).status):0;return !status}
function normalizeSlice(value:any,offeringId?:string):DeskSlice{const sessions=(value?.sessions||[]).map((s:Session)=>({...s,records:s.records&&!Array.isArray(s.records)?s.records:{}}));const finals=!value?.finals||Array.isArray(value.finals)?{}:value.finals;return {...value,offeringId:offeringId||value?.offeringId||value?.offering_id,sessions,finals}}
function recordsOf(records:Record<string,RecordEntry>|RecordEntry[]|undefined){return !records||Array.isArray(records)?{}:{...records}}
export function applyDeskMutation(slice:DeskSlice,action:string,payload:any):DeskSlice|null{
 const offeringId=slice.offeringId;
 if(action==='save_final_grade'){if(payload?.offering_id!==offeringId)return null;const key=payload.offering_id+':'+payload.module_index+':'+payload.student_id;return {...slice,finals:{...slice.finals,[key]:{continuous:payload.continuous??null,competencies:payload.competencies??[null,null],competency:payload.final_competency??null,total:payload.total??null,note:payload.note??''}}}}
 if(!slice.sessions?.some(s=>s.id===payload?.session_id))return null;
 if(action==='save_session_attendance')return {...slice,sessions:slice.sessions.map(s=>{if(s.id!==payload.session_id)return s;const records=recordsOf(s.records);for(const row of payload.records||[]){const prev=records[row.student_id]||blankRecord();records[row.student_id]={...prev,attendance:row.attendance,asked:row.asked??prev.asked,note:row.note??prev.note}}return {...s,records}})};
 if(action==='save_session_marks')return {...slice,sessions:slice.sessions.map(s=>{if(s.id!==payload.session_id)return s;const records=recordsOf(s.records);const prev=records[payload.student_id]||blankRecord();records[payload.student_id]={...prev,marks:payload.marks||[]};return {...s,records}})};
 return null;
}
async function rememberMutation(action:string,payload:any){try{for(const desk of await listCachedDesks()){const next=applyDeskMutation(normalizeSlice(desk),action,payload);if(next)await cacheDeskData(next.offeringId,next)}}catch{}}
async function postJSON(action:string,body:unknown){await ensureCsrf();const ctrl=new AbortController();const timer=setTimeout(()=>ctrl.abort(),12000);try{const r=await fetch('./school-api.php?action='+encodeURIComponent(action),{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json','X-CSRF-Token':csrf},body:JSON.stringify(body),signal:ctrl.signal});return await readBody(r)}finally{clearTimeout(timer)}}
async function queueOrSend(action:string,payload:any){await rememberMutation(action,payload);if(typeof navigator!=='undefined'&&!navigator.onLine){await enqueueMutation(action,payload);return {queued:true as const,value:null}}try{return {queued:false as const,value:await postJSON(action,payload)}}catch(error){if(!isTransportError(error))throw error;await enqueueMutation(action,payload);return {queued:true as const,value:null}}}
export function deliverDeskMutation(action:string,payload:any){if(action==='save_session_attendance'||action==='save_session_marks'||action==='save_final_grade')return postJSON(action,payload);throw Object.assign(Error('عملیات صف شناخته نشد.'),{status:422})}
function ownQueue(rows:{actor?:string;action:string;payload:any;createdAt:number;id:number}[]){const actor=offlineActor();return rows.filter(row=>!actor||!row.actor||row.actor===actor)}
export async function withQueuedEdits(slice:DeskSlice):Promise<DeskSlice>{const rows=ownQueue([...await getPendingMutations(),...await getMutationsByStatus('syncing')]).sort((a,b)=>a.createdAt-b.createdAt||a.id-b.id);let next=slice;for(const row of rows){const patched=applyDeskMutation(next,row.action,row.payload);if(patched)next=patched}return next}
export async function getDeskData(offeringId:string):Promise<DeskSlice>{if(typeof navigator!=='undefined'&&!navigator.onLine)throw Error('offline');const ctrl=new AbortController();const timer=setTimeout(()=>ctrl.abort(),8000);try{const r=await fetch('./school-api.php?action=get_desk_data&offering_id='+encodeURIComponent(offeringId),{credentials:'same-origin',signal:ctrl.signal});const slice=normalizeSlice(await readBody(r),offeringId);const queued=ownQueue([...await getPendingMutations(),...await getMutationsByStatus('syncing')]).some(row=>row.action==='save_final_grade'?row.payload?.offering_id===offeringId:slice.sessions.some(s=>s.id===row.payload?.session_id));if(!queued)await cacheDeskData(offeringId,slice).catch(()=>{});return slice}finally{clearTimeout(timer)}}
export async function saveSessionAttendance(body:DeskPlan['attendance'][number]){const result=await queueOrSend('save_session_attendance',body);if(result.queued)return {ok:true as const,dispatch:null,queued:true as const};const item=result.value?.dispatch;if(!item||typeof item!=='object')return {ok:true as const,dispatch:null,queued:false as const};const followups=item.followups&&!Array.isArray(item.followups)?item.followups:{};return {ok:true as const,dispatch:{...item,followups} as Dispatch,queued:false as const}}
export async function saveSessionMarks(body:DeskPlan['marks'][number]){const result=await queueOrSend('save_session_marks',body);return {ok:true as const,queued:result.queued}}
export async function saveFinalGrade(body:DeskPlan['finals'][number]){const result=await queueOrSend('save_final_grade',body);return {ok:true as const,queued:result.queued}}
export function collectDeskWrites(before:Data,after:Data):DeskPlan{
 const shape=(list:Session[])=>list.map(s=>({id:s.id,courseId:s.courseId,module:s.module,date:s.date,title:s.title}));
 const structural=JSON.stringify(before.courses)!==JSON.stringify(after.courses)||JSON.stringify(before.classes)!==JSON.stringify(after.classes)||JSON.stringify(before.students)!==JSON.stringify(after.students)||JSON.stringify(before.profile)!==JSON.stringify(after.profile)||JSON.stringify(shape(before.sessions))!==JSON.stringify(shape(after.sessions))||Object.keys(before.finals).some(key=>!(key in after.finals));
 const known=new Set(before.sessions.map(s=>s.id));
 const attendance:DeskPlan['attendance']=[];const marks:DeskPlan['marks']=[];const finals:DeskPlan['finals']=[];let urgent=false;
 for(const session of after.sessions){if(!known.has(session.id))continue;const prev=before.sessions.find(s=>s.id===session.id);const records:{student_id:string;attendance:string;asked:boolean;note:string}[]=[];const ids=new Set([...Object.keys(prev?.records||{}),...Object.keys(session.records||{})]);
  for(const studentId of ids){const a=prev?.records?.[studentId]||blankRecord();const b=session.records?.[studentId]||blankRecord();if(a.attendance!==b.attendance||a.asked!==b.asked||a.note!==b.note){records.push({student_id:studentId,attendance:b.attendance,asked:b.asked,note:b.note});if(a.attendance!==b.attendance||a.asked!==b.asked)urgent=true}if(JSON.stringify(a.marks)!==JSON.stringify(b.marks)){urgent=true;marks.push({session_id:session.id,student_id:studentId,marks:b.marks.map(m=>({id:m.id,type:m.type,value:m.value,max:m.max??20,note:m.note,competency:m.competency}))})}}
  if(records.length)attendance.push({session_id:session.id,records})}
 for(const [key,grade] of Object.entries(after.finals)){if(JSON.stringify(before.finals[key])===JSON.stringify(grade))continue;urgent=true;const parts=key.split(':');if(parts.length<3)continue;finals.push({offering_id:parts[0],module_index:Number(parts[1]),student_id:parts.slice(2).join(':'),continuous:grade.continuous,competencies:grade.competencies,final_competency:grade.competency,total:grade.total,note:grade.note})}
 return {structural,urgent,attendance,marks,finals}}
async function schoolGet(query:string){const r=await fetch('./school-api.php?'+query,{credentials:'same-origin'});return readBody(r)}
export function sendAttendanceSms(body:{session_id:string;student_ids:string[];pattern_code?:string}){return schoolAPI('send_attendance_sms',body)}
export function loadSmsGateway(){return schoolGet('action=sms_settings')}
export function saveSmsGateway(body:{provider:string;sender:string;pattern_code:string;api_key?:string}){return schoolAPI('sms_settings',body)}
export function loadSmsLogs(){return schoolGet('action=sms_logs')}
export function loadGradeAudit(offeringId:string,studentId:string,moduleIndex:number){return schoolGet(new URLSearchParams({action:'grade_audit',offering_id:offeringId,student_id:studentId,module_index:String(moduleIndex)}).toString())}
