import type {School} from './central-demo';import {uid,today} from './model';
export const permissions={structure:'تعریف رشته، پایه و کلاس',students:'مدیریت دانش‌آموزان',subjects:'برنامه درسی',teachers:'مدیریت معلمان',assign:'تخصیص تدریس',grades:'مشاهده نمرات و گزارش',office:'پیگیری غیبت و انضباط',routing:'تعیین مسئول حضور‌وغیاب',sms:'پیامک و مخاطبان',announce:'انتشار اطلاعیه',promotion:'انتقال سال تحصیلی'};
export type Permission=keyof typeof permissions;
export type LifeRole={id:string;name:string;permissions:Permission[]};
export type Person={id:string;name:string;roleId:string};
export type Notice={id:string;to:string;title:string;body:string;page:string;date:string;read:boolean};
export type Message={id:string;from:string;to:string;text:string;date:string;read:boolean};
export type FileAttachment={name:string;url:string;size:number};
export type Task={id:string;courseId:string;title:string;body:string;due:string;max:number;kind:'assignment'|'quiz';questions:{id:string;text:string;options:string[];correct:number}[];published:boolean};
export type Submission={id:string;taskId:string;studentId:string;text:string;file:FileAttachment|null;answers:Record<string,number>;date:string;score:number|null;feedback:string;released:boolean};
export type Dispatch={id:string;sessionId:string;yearId:string;to:string;revision:number;signature:string;date:string;title:string;rows:{id:string;name:string;status:string}[];followups:Record<string,{status:string;note:string;calls:string[]}>};
export type Contact={name:string;phone:string;group:'family'|'student'|'teacher';studentId?:string;consent:boolean};
export type Life={roles:LifeRole[];people:Person[];notices:Notice[];messages:Message[];routes:Record<string,string>;dispatches:Dispatch[];tasks:Task[];submissions:Submission[];announcements:{id:string;title:string;body:string;audience:string;date:string;by:string}[];contacts:Record<string,Contact>;sms:{id:string;date:string;text:string;targets:string[];status:'simulated';source:string}[];smsConfig:{provider:string;sender:string};notificationPrefs:Record<string,{messages:boolean;learning:boolean}>};
export function initialLife():Life{return {roles:[{id:'attendance',name:'مسئول پیگیری',permissions:['office']},{id:'counselor',name:'مشاور',permissions:['office','grades']}],people:[{id:'deputy2',name:'معاون دوم',roleId:'deputy'},{id:'staff:attendance',name:'مسئول حضور‌وغیاب',roleId:'attendance'}],notices:[{id:'welcome',to:'admin',title:'به دموی مدرسه خوش آمدید',body:'نقش‌ها، مسئول پیگیری و ارتباط با دانش‌آموز را از اینجا بررسی کنید.',page:'hub-dashboard',date:today(),read:false}],messages:[],routes:{default:'deputy'},dispatches:[],tasks:[{id:'task-demo',courseId:'o-computer-g11-computer-g11-special',title:'تمرین الگوریتم جمع دو عدد',body:'مراحل حل مسئله را بنویسید و در صورت نیاز فایل پاسخ را پیوست کنید.',due:today(),max:10,kind:'assignment',questions:[],published:true},{id:'quiz-demo',courseId:'o-computer-g11-computer-g11-special',title:'آزمون کوتاه الگوریتم',body:'به پرسش پاسخ دهید؛ نتیجه پس از ثبت نهایی نمایش داده می‌شود.',due:today(),max:5,kind:'quiz',published:true,questions:[{id:'q1',text:'اولین گام حل یک مسئله چیست؟',options:['شناخت مسئله','نوشتن کد بدون بررسی','چاپ خروجی','بستن برنامه'],correct:0}]}],submissions:[],announcements:[{id:'a1',title:'آغاز سال تحصیلی',body:'به هنرستان آذرمهر خوش آمدید. تکلیف‌ها و اطلاعیه‌های کلاس را از داشبورد خود دنبال کنید.',audience:'all',date:today(),by:'admin'}],contacts:{},sms:[],smsConfig:{provider:'سرویس انتخاب نشده',sender:''},notificationPrefs:{}}}
export function accounts(d:School,l:Life){return [{id:'admin',name:'مدیر مدرسه',roleId:'admin'},{id:'deputy',name:'معاون / ناظم',roleId:'deputy'},...l.people,...d.teachers.filter(t=>t.active).map(t=>({id:'teacher:'+t.id,name:t.name,roleId:'teacher'})),...d.students.map(s=>({id:'student:'+s.id,name:s.name+' · '+s.code,roleId:'student'}))]}
export function allowed(l:Life,actor:string,p:Permission){if(actor==='admin')return true;if(actor==='deputy'||l.people.find(x=>x.id===actor)?.roleId==='deputy')return true;const role=l.people.find(x=>x.id===actor)?.roleId;return !!l.roles.find(r=>r.id===role)?.permissions.includes(p)}
export function enrolledCourses(d:School,yearId:string,studentId:string){const e=d.enrollments.find(e=>e.yearId===yearId&&e.studentId===studentId&&e.status==='active');return d.offerings.filter(o=>o.classId===e?.classId)}
export function recipients(d:School,l:Life,actor:string,yearId:string){const all=accounts(d,l);if(actor.startsWith('student:')){const ids=new Set(enrolledCourses(d,yearId,actor.slice(8)).map(o=>'teacher:'+o.teacherId));return all.filter(p=>ids.has(p.id))}if(actor.startsWith('teacher:')){const cls=new Set(d.offerings.filter(o=>o.teacherId===actor.slice(8)&&d.classes.some(c=>c.id===o.classId&&c.yearId===yearId)).map(o=>o.classId));const ids=new Set(d.enrollments.filter(e=>e.yearId===yearId&&cls.has(e.classId||'')).map(e=>'student:'+e.studentId));return all.filter(p=>p.id!==actor&&(!p.id.startsWith('student:')||ids.has(p.id)))}return all.filter(p=>p.id!==actor&&!p.id.startsWith('student:'))}
export function notify(l:Life,to:string,title:string,body:string,page:string,kind:'messages'|'learning'|'required'='required'){if(kind!=='required'&&l.notificationPrefs[to]?.[kind]===false)return;l.notices.unshift({id:uid(),to,title,body,page,date:today(),read:false})}
export function syncAttendance(l:Life,d:School,yearId:string,teacherId:string){for(const s of d.sessions){const o=d.offerings.find(o=>o.id===s.courseId&&o.teacherId===teacherId);if(!o||!d.classes.some(c=>c.id===o.classId&&c.yearId===yearId))continue;const es=d.enrollments.filter(e=>e.classId===o.classId&&e.yearId===yearId&&e.status==='active');if(!es.length||es.some(e=>!s.records[e.studentId]||s.records[e.studentId].attendance==='unset'))continue;const rows=es.map(e=>({id:e.studentId,name:d.students.find(x=>x.id===e.studentId)!.name,status:s.records[e.studentId].attendance}));const signature=JSON.stringify(rows);let item=l.dispatches.find(x=>x.sessionId===s.id);const chosen=l.routes[o.classId]||l.routes.default;const to=chosen&&allowed(l,chosen,'office')?chosen:allowed(l,l.routes.default,'office')?l.routes.default:'admin';if(item?.signature===signature)continue;if(item){for(const r of rows)if(item.rows.find(old=>old.id===r.id)?.status!==r.status&&item.followups[r.id])item.followups[r.id].status='open';Object.assign(item,{rows,signature,revision:item.revision+1,to});}else{item={id:uid(),sessionId:s.id,yearId,to,revision:1,signature,date:s.date,title:d.classes.find(c=>c.id===o.classId)!.name+' · '+o.name,rows,followups:{}};l.dispatches.unshift(item)}notify(l,to,'حضور‌وغیاب آماده پیگیری است',item.title+' · ویرایش '+item.revision,'hub-followup')}}
export function sendMessage(l:Life,d:School,yearId:string,from:string,to:string,text:string){if(!text.trim()||!recipients(d,l,from,yearId).some(p=>p.id===to))throw Error('گیرنده معتبر و متن پیام لازم است');l.messages.push({id:uid(),from,to,text:text.trim(),date:today(),read:false});notify(l,to,'پیام جدید',accounts(d,l).find(p=>p.id===from)!.name,'hub-messages','messages')}
export function simulateSMS(l:Life,ids:string[],text:string,source:string){const targets=[...new Set(ids)].filter(id=>l.contacts[id]?.consent&&/^09\d{9}$/.test(l.contacts[id].phone));if(!text.trim()||!targets.length)throw Error('متن و حداقل یک مخاطب با شماره معتبر و رضایت دریافت لازم است');l.sms.unshift({id:uid(),date:today(),text:text.trim(),targets,status:'simulated',source})}
